import {
  nivoLineChartData,
  nivoLineChartData2,
  nivoPieChartData,
  scenario1DiagramData,
} from "component/Chat/chartDataString";

class StaticDataService {
  /** Dummy Api's **/
  getCountryCodeDetails() {
    return new Promise((resolve) => {
      resolve({
        status: 200,
        data: [
          {
            id: 1,
            flag: "https://flagcdn.com/w20/af.png",
            code: "+93",
            display: "+93 (Afghanistan)",
            countryName: "Afghanistan",
          },
          {
            id: 2,
            flag: "https://flagcdn.com/w20/al.png",
            code: "+355",
            display: "+355 (Albania)",
            countryName: "Albania",
          },
          {
            id: 3,
            flag: "https://flagcdn.com/w20/dz.png",
            code: "+213",
            display: "+213 (Algeria)",
            countryName: "Algeria",
          },
          {
            id: 4,
            flag: "https://flagcdn.com/w20/as.png",
            code: "+1684",
            display: "+1684 (American Samoa)",
            countryName: "American Samoa",
          },
          {
            id: 5,
            flag: "https://flagcdn.com/w20/ad.png",
            code: "+376",
            display: "+376 (Andorra)",
            countryName: "Andorra",
          },
          {
            id: 6,
            flag: "https://flagcdn.com/w20/ao.png",
            code: "+244",
            display: "+244 (Angola)",
            countryName: "Angola",
          },
          {
            id: 7,
            flag: "https://flagcdn.com/w20/ai.png",
            code: "+1264",
            display: "+1264 (Anguilla)",
            countryName: "Anguilla",
          },
          {
            id: 8,
            flag: "https://flagcdn.com/w20/aq.png",
            code: "+672",
            display: "+672 (Antarctica)",
            countryName: "Antarctica",
          },
          {
            id: 9,
            flag: "https://flagcdn.com/w20/ag.png",
            code: "+1268",
            display: "+1268 (Antigua and Barbuda)",
            countryName: "Antigua and Barbuda",
          },
          {
            id: 10,
            flag: "https://flagcdn.com/w20/ar.png",
            code: "+54",
            display: "+54 (Argentina)",
            countryName: "Argentina",
          },
          {
            id: 11,
            flag: "https://flagcdn.com/w20/am.png",
            code: "+374",
            display: "+374 (Armenia)",
            countryName: "Armenia",
          },
          {
            id: 12,
            flag: "https://flagcdn.com/w20/aw.png",
            code: "+297",
            display: "+297 (Aruba)",
            countryName: "Aruba",
          },
          {
            id: 13,
            flag: "https://flagcdn.com/w20/au.png",
            code: "+61",
            display: "+61 (Australia)",
            countryName: "Australia",
          },
          {
            id: 14,
            flag: "https://flagcdn.com/w20/at.png",
            code: "+43",
            display: "+43 (Austria)",
            countryName: "Austria",
          },
          {
            id: 15,
            flag: "https://flagcdn.com/w20/az.png",
            code: "+994",
            display: "+994 (Azerbaijan)",
            countryName: "Azerbaijan",
          },
          {
            id: 16,
            flag: "https://flagcdn.com/w20/bs.png",
            code: "+1242",
            display: "+1242 (Bahamas)",
            countryName: "Bahamas",
          },
          {
            id: 17,
            flag: "https://flagcdn.com/w20/bh.png",
            code: "+973",
            display: "+973 (Bahrain)",
            countryName: "Bahrain",
          },
          {
            id: 18,
            flag: "https://flagcdn.com/w20/bd.png",
            code: "+880",
            display: "+880 (Bangladesh)",
            countryName: "Bangladesh",
          },
          {
            id: 19,
            flag: "https://flagcdn.com/w20/bb.png",
            code: "+1246",
            display: "+1246 (Barbados)",
            countryName: "Barbados",
          },
          {
            id: 20,
            flag: "https://flagcdn.com/w20/by.png",
            code: "+375",
            display: "+375 (Belarus)",
            countryName: "Belarus",
          },
          {
            id: 21,
            flag: "https://flagcdn.com/w20/be.png",
            code: "+32",
            display: "+32 (Belgium)",
            countryName: "Belgium",
          },
          {
            id: 22,
            flag: "https://flagcdn.com/w20/bz.png",
            code: "+501",
            display: "+501 (Belize)",
            countryName: "Belize",
          },
          {
            id: 23,
            flag: "https://flagcdn.com/w20/bj.png",
            code: "+229",
            display: "+229 (Benin)",
            countryName: "Benin",
          },
          {
            id: 24,
            flag: "https://flagcdn.com/w20/bm.png",
            code: "+1441",
            display: "+1441 (Bermuda)",
            countryName: "Bermuda",
          },
          {
            id: 25,
            flag: "https://flagcdn.com/w20/bt.png",
            code: "+975",
            display: "+975 (Bhutan)",
            countryName: "Bhutan",
          },
          {
            id: 26,
            flag: "https://flagcdn.com/w20/bo.png",
            code: "+591",
            display: "+591 (Bolivia)",
            countryName: "Bolivia",
          },
          {
            id: 27,
            flag: "https://flagcdn.com/w20/ba.png",
            code: "+387",
            display: "+387 (Bosnia and Herzegovina)",
            countryName: "Bosnia and Herzegovina",
          },
          {
            id: 28,
            flag: "https://flagcdn.com/w20/bw.png",
            code: "+267",
            display: "+267 (Botswana)",
            countryName: "Botswana",
          },
          {
            id: 29,
            flag: "https://flagcdn.com/w20/br.png",
            code: "+55",
            display: "+55 (Brazil)",
            countryName: "Brazil",
          },
          {
            id: 30,
            flag: "https://flagcdn.com/w20/io.png",
            code: "+246",
            display: "+246 (British Indian Ocean Territory)",
            countryName: "British Indian Ocean Territory",
          },
          {
            id: 31,
            flag: "https://flagcdn.com/w20/vg.png",
            code: "+1284",
            display: "+1284 (British Virgin Islands)",
            countryName: "British Virgin Islands",
          },
          {
            id: 32,
            flag: "https://flagcdn.com/w20/bn.png",
            code: "+673",
            display: "+673 (Brunei)",
            countryName: "Brunei",
          },
          {
            id: 33,
            flag: "https://flagcdn.com/w20/bg.png",
            code: "+359",
            display: "+359 (Bulgaria)",
            countryName: "Bulgaria",
          },
          {
            id: 34,
            flag: "https://flagcdn.com/w20/bf.png",
            code: "+226",
            display: "+226 (Burkina Faso)",
            countryName: "Burkina Faso",
          },
          {
            id: 35,
            flag: "https://flagcdn.com/w20/bi.png",
            code: "+257",
            display: "+257 (Burundi)",
            countryName: "Burundi",
          },
          {
            id: 36,
            flag: "https://flagcdn.com/w20/kh.png",
            code: "+855",
            display: "+855 (Cambodia)",
            countryName: "Cambodia",
          },
          {
            id: 37,
            flag: "https://flagcdn.com/w20/cm.png",
            code: "+237",
            display: "+237 (Cameroon)",
            countryName: "Cameroon",
          },
          {
            id: 38,
            flag: "https://flagcdn.com/w20/ca.png",
            code: "+1",
            display: "+1 (Canada)",
            countryName: "Canada",
          },
          {
            id: 39,
            flag: "https://flagcdn.com/w20/cv.png",
            code: "+238",
            display: "+238 (Cape Verde)",
            countryName: "Cape Verde",
          },
          {
            id: 40,
            flag: "https://flagcdn.com/w20/ky.png",
            code: "+1345",
            display: "+1345 (Cayman Islands)",
            countryName: "Cayman Islands",
          },
          {
            id: 41,
            flag: "https://flagcdn.com/w20/cf.png",
            code: "+236",
            display: "+236 (Central African Republic)",
            countryName: "Central African Republic",
          },
          {
            id: 42,
            flag: "https://flagcdn.com/w20/td.png",
            code: "+235",
            display: "+235 (Chad)",
            countryName: "Chad",
          },
          {
            id: 43,
            flag: "https://flagcdn.com/w20/cl.png",
            code: "+56",
            display: "+56 (Chile)",
            countryName: "Chile",
          },
          {
            id: 44,
            flag: "https://flagcdn.com/w20/cn.png",
            code: "+86",
            display: "+86 (China)",
            countryName: "China",
          },
          {
            id: 45,
            flag: "https://flagcdn.com/w20/cx.png",
            code: "+61",
            display: "+61 (Christmas Island)",
            countryName: "Christmas Island",
          },
          {
            id: 46,
            flag: "https://flagcdn.com/w20/cc.png",
            code: "+61",
            display: "+61 (Cocos Islands)",
            countryName: "Cocos Islands",
          },
          {
            id: 47,
            flag: "https://flagcdn.com/w20/co.png",
            code: "+57",
            display: "+57 (Colombia)",
            countryName: "Colombia",
          },
          {
            id: 48,
            flag: "https://flagcdn.com/w20/km.png",
            code: "+269",
            display: "+269 (Comoros)",
            countryName: "Comoros",
          },
          {
            id: 49,
            flag: "https://flagcdn.com/w20/ck.png",
            code: "+682",
            display: "+682 (Cook Islands)",
            countryName: "Cook Islands",
          },
          {
            id: 50,
            flag: "https://flagcdn.com/w20/cr.png",
            code: "+506",
            display: "+506 (Costa Rica)",
            countryName: "Costa Rica",
          },
          {
            id: 51,
            flag: "https://flagcdn.com/w20/hr.png",
            code: "+385",
            display: "+385 (Croatia)",
            countryName: "Croatia",
          },
          {
            id: 52,
            flag: "https://flagcdn.com/w20/cu.png",
            code: "+53",
            display: "+53 (Cuba)",
            countryName: "Cuba",
          },
          {
            id: 53,
            flag: "https://flagcdn.com/w20/cw.png",
            code: "+599",
            display: "+599 (Curacao)",
            countryName: "Curacao",
          },
          {
            id: 54,
            flag: "https://flagcdn.com/w20/cy.png",
            code: "+357",
            display: "+357 (Cyprus)",
            countryName: "Cyprus",
          },
          {
            id: 55,
            flag: "https://flagcdn.com/w20/cz.png",
            code: "+420",
            display: "+420 (Czech Republic)",
            countryName: "Czech Republic",
          },
          {
            id: 56,
            flag: "https://flagcdn.com/w20/cd.png",
            code: "+243",
            display: "+243 (Democratic Republic of the Congo)",
            countryName: "Democratic Republic of the Congo",
          },
          {
            id: 57,
            flag: "https://flagcdn.com/w20/dk.png",
            code: "+45",
            display: "+45 (Denmark)",
            countryName: "Denmark",
          },
          {
            id: 58,
            flag: "https://flagcdn.com/w20/dj.png",
            code: "+253",
            display: "+253 (Djibouti)",
            countryName: "Djibouti",
          },
          {
            id: 59,
            flag: "https://flagcdn.com/w20/dm.png",
            code: "+1767",
            display: "+1767 (Dominica)",
            countryName: "Dominica",
          },
          {
            id: 60,
            flag: "https://flagcdn.com/w20/do.png",
            code: "+1",
            display: "+1 (Dominican Republic)",
            countryName: "Dominican Republic",
          },
          {
            id: 61,
            flag: "https://flagcdn.com/w20/tl.png",
            code: "+670",
            display: "+670 (East Timor)",
            countryName: "East Timor",
          },
          {
            id: 62,
            flag: "https://flagcdn.com/w20/ec.png",
            code: "+593",
            display: "+593 (Ecuador)",
            countryName: "Ecuador",
          },
          {
            id: 63,
            flag: "https://flagcdn.com/w20/eg.png",
            code: "+20",
            display: "+20 (Egypt)",
            countryName: "Egypt",
          },
          {
            id: 64,
            flag: "https://flagcdn.com/w20/sv.png",
            code: "+503",
            display: "+503 (El Salvador)",
            countryName: "El Salvador",
          },
          {
            id: 65,
            flag: "https://flagcdn.com/w20/gq.png",
            code: "+240",
            display: "+240 (Equatorial Guinea)",
            countryName: "Equatorial Guinea",
          },
          {
            id: 66,
            flag: "https://flagcdn.com/w20/er.png",
            code: "+291",
            display: "+291 (Eritrea)",
            countryName: "Eritrea",
          },
          {
            id: 67,
            flag: "https://flagcdn.com/w20/ee.png",
            code: "+372",
            display: "+372 (Estonia)",
            countryName: "Estonia",
          },
          {
            id: 68,
            flag: "https://flagcdn.com/w20/et.png",
            code: "+251",
            display: "+251 (Ethiopia)",
            countryName: "Ethiopia",
          },
          {
            id: 69,
            flag: "https://flagcdn.com/w20/fk.png",
            code: "+500",
            display: "+500 (Falkland Islands)",
            countryName: "Falkland Islands",
          },
          {
            id: 70,
            flag: "https://flagcdn.com/w20/fo.png",
            code: "+298",
            display: "+298 (Faroe Islands)",
            countryName: "Faroe Islands",
          },
          {
            id: 71,
            flag: "https://flagcdn.com/w20/fj.png",
            code: "+679",
            display: "+679 (Fiji)",
            countryName: "Fiji",
          },
          {
            id: 72,
            flag: "https://flagcdn.com/w20/fi.png",
            code: "+358",
            display: "+358 (Finland)",
            countryName: "Finland",
          },
          {
            id: 73,
            flag: "https://flagcdn.com/w20/fr.png",
            code: "+33",
            display: "+33 (France)",
            countryName: "France",
          },
          {
            id: 74,
            flag: "https://flagcdn.com/w20/pf.png",
            code: "+689",
            display: "+689 (French Polynesia)",
            countryName: "French Polynesia",
          },
          {
            id: 75,
            flag: "https://flagcdn.com/w20/ga.png",
            code: "+241",
            display: "+241 (Gabon)",
            countryName: "Gabon",
          },
          {
            id: 76,
            flag: "https://flagcdn.com/w20/gm.png",
            code: "+220",
            display: "+220 (Gambia)",
            countryName: "Gambia",
          },
          {
            id: 77,
            flag: "https://flagcdn.com/w20/ge.png",
            code: "+995",
            display: "+995 (Georgia)",
            countryName: "Georgia",
          },
          {
            id: 78,
            flag: "https://flagcdn.com/w20/de.png",
            code: "+49",
            display: "+49 (Germany)",
            countryName: "Germany",
          },
          {
            id: 79,
            flag: "https://flagcdn.com/w20/gh.png",
            code: "+233",
            display: "+233 (Ghana)",
            countryName: "Ghana",
          },
          {
            id: 80,
            flag: "https://flagcdn.com/w20/gi.png",
            code: "+350",
            display: "+350 (Gibraltar)",
            countryName: "Gibraltar",
          },
          {
            id: 81,
            flag: "https://flagcdn.com/w20/gr.png",
            code: "+30",
            display: "+30 (Greece)",
            countryName: "Greece",
          },
          {
            id: 82,
            flag: "https://flagcdn.com/w20/gl.png",
            code: "+299",
            display: "+299 (Greenland)",
            countryName: "Greenland",
          },
          {
            id: 83,
            flag: "https://flagcdn.com/w20/gd.png",
            code: "+1473",
            display: "+1473 (Grenada)",
            countryName: "Grenada",
          },
          {
            id: 84,
            flag: "https://flagcdn.com/w20/gu.png",
            code: "+1671",
            display: "+1671 (Guam)",
            countryName: "Guam",
          },
          {
            id: 85,
            flag: "https://flagcdn.com/w20/gt.png",
            code: "+502",
            display: "+502 (Guatemala)",
            countryName: "Guatemala",
          },
          {
            id: 86,
            flag: "https://flagcdn.com/w20/gg.png",
            code: "+4414",
            display: "+4414 (Guernsey)",
            countryName: "Guernsey",
          },
          {
            id: 87,
            flag: "https://flagcdn.com/w20/gn.png",
            code: "+224",
            display: "+224 (Guinea)",
            countryName: "Guinea",
          },
          {
            id: 88,
            flag: "https://flagcdn.com/w20/gw.png",
            code: "+245",
            display: "+245 (Guinea-Bissau)",
            countryName: "Guinea-Bissau",
          },
          {
            id: 89,
            flag: "https://flagcdn.com/w20/gy.png",
            code: "+592",
            display: "+592 (Guyana)",
            countryName: "Guyana",
          },
          {
            id: 90,
            flag: "https://flagcdn.com/w20/ht.png",
            code: "+509",
            display: "+509 (Haiti)",
            countryName: "Haiti",
          },
          {
            id: 91,
            flag: "https://flagcdn.com/w20/hn.png",
            code: "+504",
            display: "+504 (Honduras)",
            countryName: "Honduras",
          },
          {
            id: 92,
            flag: "https://flagcdn.com/w20/hk.png",
            code: "+852",
            display: "+852 (Hong Kong)",
            countryName: "Hong Kong",
          },
          {
            id: 93,
            flag: "https://flagcdn.com/w20/hu.png",
            code: "+36",
            display: "+36 (Hungary)",
            countryName: "Hungary",
          },
          {
            id: 94,
            flag: "https://flagcdn.com/w20/is.png",
            code: "+354",
            display: "+354 (Iceland)",
            countryName: "Iceland",
          },
          {
            id: 95,
            flag: "https://flagcdn.com/w20/in.png",
            code: "+91",
            display: "+91 (India)",
            countryName: "India",
          },
          {
            id: 96,
            flag: "https://flagcdn.com/w20/id.png",
            code: "+62",
            display: "+62 (Indonesia)",
            countryName: "Indonesia",
          },
          {
            id: 97,
            flag: "https://flagcdn.com/w20/ir.png",
            code: "+98",
            display: "+98 (Iran)",
            countryName: "Iran",
          },
          {
            id: 98,
            flag: "https://flagcdn.com/w20/iq.png",
            code: "+964",
            display: "+964 (Iraq)",
            countryName: "Iraq",
          },
          {
            id: 99,
            flag: "https://flagcdn.com/w20/ie.png",
            code: "+353",
            display: "+353 (Ireland)",
            countryName: "Ireland",
          },
          {
            id: 100,
            flag: "https://flagcdn.com/w20/im.png",
            code: "+4416",
            display: "+4416 (Isle of Man)",
            countryName: "Isle of Man",
          },
          {
            id: 101,
            flag: "https://flagcdn.com/w20/il.png",
            code: "+972",
            display: "+972 (Israel)",
            countryName: "Israel",
          },
          {
            id: 102,
            flag: "https://flagcdn.com/w20/it.png",
            code: "+39",
            display: "+39 (Italy)",
            countryName: "Italy",
          },
          {
            id: 103,
            flag: "https://flagcdn.com/w20/ci.png",
            code: "+225",
            display: "+225 (Ivory Coast)",
            countryName: "Ivory Coast",
          },
          {
            id: 104,
            flag: "https://flagcdn.com/w20/jm.png",
            code: "+1876",
            display: "+1876 (Jamaica)",
            countryName: "Jamaica",
          },
          {
            id: 105,
            flag: "https://flagcdn.com/w20/jp.png",
            code: "+81",
            display: "+81 (Japan)",
            countryName: "Japan",
          },
          {
            id: 106,
            flag: "https://flagcdn.com/w20/je.png",
            code: "+4415",
            display: "+4415 (Jersey)",
            countryName: "Jersey",
          },
          {
            id: 107,
            flag: "https://flagcdn.com/w20/jo.png",
            code: "+962",
            display: "+962 (Jordan)",
            countryName: "Jordan",
          },
          {
            id: 108,
            flag: "https://flagcdn.com/w20/kz.png",
            code: "+7",
            display: "+7 (Kazakhstan)",
            countryName: "Kazakhstan",
          },
          {
            id: 109,
            flag: "https://flagcdn.com/w20/ke.png",
            code: "+254",
            display: "+254 (Kenya)",
            countryName: "Kenya",
          },
          {
            id: 110,
            flag: "https://flagcdn.com/w20/ki.png",
            code: "+686",
            display: "+686 (Kiribati)",
            countryName: "Kiribati",
          },
          {
            id: 111,
            flag: "https://flagcdn.com/w20/xk.png",
            code: "+383",
            display: "+383 (Kosovo)",
            countryName: "Kosovo",
          },
          {
            id: 112,
            flag: "https://flagcdn.com/w20/kw.png",
            code: "+965",
            display: "+965 (Kuwait)",
            countryName: "Kuwait",
          },
          {
            id: 113,
            flag: "https://flagcdn.com/w20/kg.png",
            code: "+996",
            display: "+996 (Kyrgyzstan)",
            countryName: "Kyrgyzstan",
          },
          {
            id: 114,
            flag: "https://flagcdn.com/w20/la.png",
            code: "+856",
            display: "+856 (Laos)",
            countryName: "Laos",
          },
          {
            id: 115,
            flag: "https://flagcdn.com/w20/lv.png",
            code: "+371",
            display: "+371 (Latvia)",
            countryName: "Latvia",
          },
          {
            id: 116,
            flag: "https://flagcdn.com/w20/lb.png",
            code: "+961",
            display: "+961 (Lebanon)",
            countryName: "Lebanon",
          },
          {
            id: 117,
            flag: "https://flagcdn.com/w20/ls.png",
            code: "+266",
            display: "+266 (Lesotho)",
            countryName: "Lesotho",
          },
          {
            id: 118,
            flag: "https://flagcdn.com/w20/lr.png",
            code: "+231",
            display: "+231 (Liberia)",
            countryName: "Liberia",
          },
          {
            id: 119,
            flag: "https://flagcdn.com/w20/ly.png",
            code: "+218",
            display: "+218 (Libya)",
            countryName: "Libya",
          },
          {
            id: 120,
            flag: "https://flagcdn.com/w20/li.png",
            code: "+423",
            display: "+423 (Liechtenstein)",
            countryName: "Liechtenstein",
          },
          {
            id: 121,
            flag: "https://flagcdn.com/w20/lt.png",
            code: "+370",
            display: "+370 (Lithuania)",
            countryName: "Lithuania",
          },
          {
            id: 122,
            flag: "https://flagcdn.com/w20/lu.png",
            code: "+352",
            display: "+352 (Luxembourg)",
            countryName: "Luxembourg",
          },
          {
            id: 123,
            flag: "https://flagcdn.com/w20/mo.png",
            code: "+853",
            display: "+853 (Macau)",
            countryName: "Macau",
          },
          {
            id: 124,
            flag: "https://flagcdn.com/w20/mk.png",
            code: "+389",
            display: "+389 (Macedonia)",
            countryName: "Macedonia",
          },
          {
            id: 125,
            flag: "https://flagcdn.com/w20/mg.png",
            code: "+261",
            display: "+261 (Madagascar)",
            countryName: "Madagascar",
          },
          {
            id: 126,
            flag: "https://flagcdn.com/w20/mw.png",
            code: "+265",
            display: "+265 (Malawi)",
            countryName: "Malawi",
          },
          {
            id: 127,
            flag: "https://flagcdn.com/w20/my.png",
            code: "+60",
            display: "+60 (Malaysia)",
            countryName: "Malaysia",
          },
          {
            id: 128,
            flag: "https://flagcdn.com/w20/mv.png",
            code: "+960",
            display: "+960 (Maldives)",
            countryName: "Maldives",
          },
          {
            id: 129,
            flag: "https://flagcdn.com/w20/ml.png",
            code: "+223",
            display: "+223 (Mali)",
            countryName: "Mali",
          },
          {
            id: 130,
            flag: "https://flagcdn.com/w20/mt.png",
            code: "+356",
            display: "+356 (Malta)",
            countryName: "Malta",
          },
          {
            id: 131,
            flag: "https://flagcdn.com/w20/mh.png",
            code: "+692",
            display: "+692 (Marshall Islands)",
            countryName: "Marshall Islands",
          },
          {
            id: 132,
            flag: "https://flagcdn.com/w20/mr.png",
            code: "+222",
            display: "+222 (Mauritania)",
            countryName: "Mauritania",
          },
          {
            id: 133,
            flag: "https://flagcdn.com/w20/mu.png",
            code: "+230",
            display: "+230 (Mauritius)",
            countryName: "Mauritius",
          },
          {
            id: 134,
            flag: "https://flagcdn.com/w20/yt.png",
            code: "+262",
            display: "+262 (Mayotte)",
            countryName: "Mayotte",
          },
          {
            id: 135,
            flag: "https://flagcdn.com/w20/mx.png",
            code: "+52",
            display: "+52 (Mexico)",
            countryName: "Mexico",
          },
          {
            id: 136,
            flag: "https://flagcdn.com/w20/fm.png",
            code: "+691",
            display: "+691 (Micronesia)",
            countryName: "Micronesia",
          },
          {
            id: 137,
            flag: "https://flagcdn.com/w20/md.png",
            code: "+373",
            display: "+373 (Moldova)",
            countryName: "Moldova",
          },
          {
            id: 138,
            flag: "https://flagcdn.com/w20/mc.png",
            code: "+377",
            display: "+377 (Monaco)",
            countryName: "Monaco",
          },
          {
            id: 139,
            flag: "https://flagcdn.com/w20/mn.png",
            code: "+976",
            display: "+976 (Mongolia)",
            countryName: "Mongolia",
          },
          {
            id: 140,
            flag: "https://flagcdn.com/w20/me.png",
            code: "+382",
            display: "+382 (Montenegro)",
            countryName: "Montenegro",
          },
          {
            id: 141,
            flag: "https://flagcdn.com/w20/ms.png",
            code: "+1664",
            display: "+1664 (Montserrat)",
            countryName: "Montserrat",
          },
          {
            id: 142,
            flag: "https://flagcdn.com/w20/ma.png",
            code: "+212",
            display: "+212 (Morocco)",
            countryName: "Morocco",
          },
          {
            id: 143,
            flag: "https://flagcdn.com/w20/mz.png",
            code: "+258",
            display: "+258 (Mozambique)",
            countryName: "Mozambique",
          },
          {
            id: 144,
            flag: "https://flagcdn.com/w20/mm.png",
            code: "+95",
            display: "+95 (Myanmar)",
            countryName: "Myanmar",
          },
          {
            id: 145,
            flag: "https://flagcdn.com/w20/na.png",
            code: "+264",
            display: "+264 (Namibia)",
            countryName: "Namibia",
          },
          {
            id: 146,
            flag: "https://flagcdn.com/w20/nr.png",
            code: "+674",
            display: "+674 (Nauru)",
            countryName: "Nauru",
          },
          {
            id: 147,
            flag: "https://flagcdn.com/w20/np.png",
            code: "+977",
            display: "+977 (Nepal)",
            countryName: "Nepal",
          },
          {
            id: 148,
            flag: "https://flagcdn.com/w20/nl.png",
            code: "+31",
            display: "+31 (Netherlands)",
            countryName: "Netherlands",
          },
          {
            id: 149,
            flag: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Flag_of_the_Netherlands_Antilles_(1959%E2%80%931986).svg",
            code: "+599",
            display: "+599 (Netherlands Antilles)",
            countryName: "Netherlands Antilles",
          },
          {
            id: 150,
            flag: "https://flagcdn.com/w20/nc.png",
            code: "+687",
            display: "+687 (New Caledonia)",
            countryName: "New Caledonia",
          },
          {
            id: 151,
            flag: "https://flagcdn.com/w20/nz.png",
            code: "+64",
            display: "+64 (New Zealand)",
            countryName: "New Zealand",
          },
          {
            id: 152,
            flag: "https://flagcdn.com/w20/ni.png",
            code: "+505",
            display: "+505 (Nicaragua)",
            countryName: "Nicaragua",
          },
          {
            id: 153,
            flag: "https://flagcdn.com/w20/ne.png",
            code: "+227",
            display: "+227 (Niger)",
            countryName: "Niger",
          },
          {
            id: 154,
            flag: "https://flagcdn.com/w20/ng.png",
            code: "+234",
            display: "+234 (Nigeria)",
            countryName: "Nigeria",
          },
          {
            id: 155,
            flag: "https://flagcdn.com/w20/nu.png",
            code: "+683",
            display: "+683 (Niue)",
            countryName: "Niue",
          },
          {
            id: 156,
            flag: "https://flagcdn.com/w20/kp.png",
            code: "+850",
            display: "+850 (North Korea)",
            countryName: "North Korea",
          },
          {
            id: 157,
            // flag: "https://flagcdn.com/w20/mp.png",
            flag: "https://flagcdn.com/mp.svg",
            code: "+1670",
            display: "+1670 (Northern Mariana Islands)",
            countryName: "Northern Mariana Islands",
          },
          {
            id: 158,
            flag: "https://flagcdn.com/w20/no.png",
            code: "+47",
            display: "+47 (Norway)",
            countryName: "Norway",
          },
          {
            id: 159,
            flag: "https://flagcdn.com/w20/om.png",
            code: "+968",
            display: "+968 (Oman)",
            countryName: "Oman",
          },
          {
            id: 160,
            flag: "https://flagcdn.com/w20/pk.png",
            code: "+92",
            display: "+92 (Pakistan)",
            countryName: "Pakistan",
          },
          {
            id: 161,
            flag: "https://flagcdn.com/w20/pw.png",
            code: "+680",
            display: "+680 (Palau)",
            countryName: "Palau",
          },
          {
            id: 162,
            flag: "https://flagcdn.com/w20/ps.png",
            code: "+970",
            display: "+970 (Palestine)",
            countryName: "Palestine",
          },
          {
            id: 163,
            flag: "https://flagcdn.com/w20/pa.png",
            code: "+507",
            display: "+507 (Panama)",
            countryName: "Panama",
          },
          {
            id: 164,
            flag: "https://flagcdn.com/w20/pg.png",
            code: "+675",
            display: "+675 (Papua New Guinea)",
            countryName: "Papua New Guinea",
          },
          {
            id: 165,
            flag: "https://flagcdn.com/w20/py.png",
            code: "+595",
            display: "+595 (Paraguay)",
            countryName: "Paraguay",
          },
          {
            id: 166,
            flag: "https://flagcdn.com/w20/pe.png",
            code: "+51",
            display: "+51 (Peru)",
            countryName: "Peru",
          },
          {
            id: 167,
            flag: "https://flagcdn.com/w20/ph.png",
            code: "+63",
            display: "+63 (Philippines)",
            countryName: "Philippines",
          },
          {
            id: 168,
            flag: "https://flagcdn.com/w20/pn.png",
            code: "+64",
            display: "+64 (Pitcairn)",
            countryName: "Pitcairn",
          },
          {
            id: 169,
            flag: "https://flagcdn.com/w20/pl.png",
            code: "+48",
            display: "+48 (Poland)",
            countryName: "Poland",
          },
          {
            id: 170,
            flag: "https://flagcdn.com/w20/pt.png",
            code: "+351",
            display: "+351 (Portugal)",
            countryName: "Portugal",
          },
          {
            id: 171,
            flag: "https://flagcdn.com/w20/pr.png",
            code: "+1",
            display: "+1 (Puerto Rico)",
            countryName: "Puerto Rico",
          },
          {
            id: 172,
            flag: "https://flagcdn.com/w20/qa.png",
            code: "+974",
            display: "+974 (Qatar)",
            countryName: "Qatar",
          },
          {
            id: 173,
            flag: "https://flagcdn.com/w20/cg.png",
            code: "+242",
            display: "+242 (Republic of the Congo)",
            countryName: "Republic of the Congo",
          },
          {
            id: 174,
            flag: "https://flagcdn.com/w20/re.png",
            code: "+262",
            display: "+262 (Reunion)",
            countryName: "Reunion",
          },
          {
            id: 175,
            flag: "https://flagcdn.com/w20/ro.png",
            code: "+40",
            display: "+40 (Romania)",
            countryName: "Romania",
          },
          {
            id: 176,
            flag: "https://flagcdn.com/w20/ru.png",
            code: "+7",
            display: "+7 (Russia)",
            countryName: "Russia",
          },
          {
            id: 177,
            flag: "https://flagcdn.com/w20/rw.png",
            code: "+250",
            display: "+250 (Rwanda)",
            countryName: "Rwanda",
          },
          {
            id: 178,
            flag: "https://flagcdn.com/w20/bl.png",
            code: "+590",
            display: "+590 (Saint Barthelemy)",
            countryName: "Saint Barthelemy",
          },
          {
            id: 179,
            flag: "https://flagcdn.com/w20/sh.png",
            code: "+290",
            display: "+290 (Saint Helena)",
            countryName: "Saint Helena",
          },
          {
            id: 180,
            flag: "https://flagcdn.com/w20/kn.png",
            code: "+1869",
            display: "+1869 (Saint Kitts and Nevis)",
            countryName: "Saint Kitts and Nevis",
          },
          {
            id: 181,
            flag: "https://flagcdn.com/w20/lc.png",
            code: "+1758",
            display: "+1758 (Saint Lucia)",
            countryName: "Saint Lucia",
          },
          {
            id: 182,
            flag: "https://flagcdn.com/w20/mf.png",
            code: "+590",
            display: "+590 (Saint Martin)",
            countryName: "Saint Martin",
          },
          {
            id: 183,
            flag: "https://flagcdn.com/w20/pm.png",
            code: "+508",
            display: "+508 (Saint Pierre and Miquelon)",
            countryName: "Saint Pierre and Miquelon",
          },
          {
            id: 184,
            flag: "https://flagcdn.com/w20/vc.png",
            code: "+1784",
            display: "+1784 (Saint Vincent and the Grenadines)",
            countryName: "Saint Vincent and the Grenadines",
          },
          {
            id: 185,
            flag: "https://flagcdn.com/w20/ws.png",
            code: "+685",
            display: "+685 (Samoa)",
            countryName: "Samoa",
          },
          {
            id: 186,
            flag: "https://flagcdn.com/w20/sm.png",
            code: "+378",
            display: "+378 (San Marino)",
            countryName: "San Marino",
          },
          {
            id: 187,
            flag: "https://flagcdn.com/w20/st.png",
            code: "+239",
            display: "+239 (Sao Tome and Principe)",
            countryName: "Sao Tome and Principe",
          },
          {
            id: 188,
            flag: "https://flagcdn.com/w20/sa.png",
            code: "+966",
            display: "+966 (Saudi Arabia)",
            countryName: "Saudi Arabia",
          },
          {
            id: 189,
            flag: "https://flagcdn.com/w20/sn.png",
            code: "+221",
            display: "+221 (Senegal)",
            countryName: "Senegal",
          },
          {
            id: 190,
            flag: "https://flagcdn.com/w20/rs.png",
            code: "+381",
            display: "+381 (Serbia)",
            countryName: "Serbia",
          },
          {
            id: 191,
            flag: "https://flagcdn.com/w20/sc.png",
            code: "+248",
            display: "+248 (Seychelles)",
            countryName: "Seychelles",
          },
          {
            id: 192,
            flag: "https://flagcdn.com/w20/sl.png",
            code: "+232",
            display: "+232 (Sierra Leone)",
            countryName: "Sierra Leone",
          },
          {
            id: 193,
            flag: "https://flagcdn.com/w20/sg.png",
            code: "+65",
            display: "+65 (Singapore)",
            countryName: "Singapore",
          },
          {
            id: 194,
            flag: "https://flagcdn.com/w20/sx.png",
            code: "+1721",
            display: "+1721 (Sint Maarten)",
            countryName: "Sint Maarten",
          },
          {
            id: 195,
            flag: "https://flagcdn.com/w20/sk.png",
            code: "+421",
            display: "+421 (Slovakia)",
            countryName: "Slovakia",
          },
          {
            id: 196,
            flag: "https://flagcdn.com/w20/si.png",
            code: "+386",
            display: "+386 (Slovenia)",
            countryName: "Slovenia",
          },
          {
            id: 197,
            flag: "https://flagcdn.com/w20/sb.png",
            code: "+677",
            display: "+677 (Solomon Islands)",
            countryName: "Solomon Islands",
          },
          {
            id: 198,
            flag: "https://flagcdn.com/w20/so.png",
            code: "+252",
            display: "+252 (Somalia)",
            countryName: "Somalia",
          },
          {
            id: 199,
            flag: "https://flagcdn.com/w20/za.png",
            code: "+27",
            display: "+27 (South Africa)",
            countryName: "South Africa",
          },
          {
            id: 200,
            flag: "https://flagcdn.com/w20/kr.png",
            code: "+82",
            display: "+82 (South Korea)",
            countryName: "South Korea",
          },
          {
            id: 201,
            flag: "https://flagcdn.com/w20/ss.png",
            code: "+211",
            display: "+211 (South Sudan)",
            countryName: "South Sudan",
          },
          {
            id: 202,
            flag: "https://flagcdn.com/w20/es.png",
            code: "+34",
            display: "+34 (Spain)",
            countryName: "Spain",
          },
          {
            id: 203,
            flag: "https://flagcdn.com/w20/lk.png",
            code: "+94",
            display: "+94 (Sri Lanka)",
            countryName: "Sri Lanka",
          },
          {
            id: 204,
            flag: "https://flagcdn.com/w20/sd.png",
            code: "+249",
            display: "+249 (Sudan)",
            countryName: "Sudan",
          },
          {
            id: 205,
            flag: "https://flagcdn.com/w20/sr.png",
            code: "+597",
            display: "+597 (Suriname)",
            countryName: "Suriname",
          },
          {
            id: 206,
            flag: "https://flagcdn.com/w20/sj.png",
            code: "+47",
            display: "+47 (Svalbard and Jan Mayen)",
            countryName: "Svalbard and Jan Mayen",
          },
          {
            id: 207,
            flag: "https://flagcdn.com/w20/sz.png",
            code: "+268",
            display: "+268 (Swaziland)",
            countryName: "Swaziland",
          },
          {
            id: 208,
            flag: "https://flagcdn.com/w20/se.png",
            code: "+46",
            display: "+46 (Sweden)",
            countryName: "Sweden",
          },
          {
            id: 209,
            flag: "https://flagcdn.com/w20/ch.png",
            code: "+41",
            display: "+41 (Switzerland)",
            countryName: "Switzerland",
          },
          {
            id: 210,
            flag: "https://flagcdn.com/w20/sy.png",
            code: "+963",
            display: "+963 (Syria)",
            countryName: "Syria",
          },
          {
            id: 211,
            flag: "https://flagcdn.com/w20/tw.png",
            code: "+886",
            display: "+886 (Taiwan)",
            countryName: "Taiwan",
          },
          {
            id: 212,
            flag: "https://flagcdn.com/w20/tj.png",
            code: "+992",
            display: "+992 (Tajikistan)",
            countryName: "Tajikistan",
          },
          {
            id: 213,
            flag: "https://flagcdn.com/w20/tz.png",
            code: "+255",
            display: "+255 (Tanzania)",
            countryName: "Tanzania",
          },
          {
            id: 214,
            flag: "https://flagcdn.com/w20/th.png",
            code: "+66",
            display: "+66 (Thailand)",
            countryName: "Thailand",
          },
          {
            id: 215,
            flag: "https://flagcdn.com/w20/tg.png",
            code: "+228",
            display: "+228 (Togo)",
            countryName: "Togo",
          },
          {
            id: 216,
            flag: "https://flagcdn.com/w20/tk.png",
            code: "+690",
            display: "+690 (Tokelau)",
            countryName: "Tokelau",
          },
          {
            id: 217,
            flag: "https://flagcdn.com/w20/to.png",
            code: "+676",
            display: "+676 (Tonga)",
            countryName: "Tonga",
          },
          {
            id: 218,
            flag: "https://flagcdn.com/w20/tt.png",
            code: "+1868",
            display: "+1868 (Trinidad and Tobago)",
            countryName: "Trinidad and Tobago",
          },
          {
            id: 219,
            flag: "https://flagcdn.com/w20/tn.png",
            code: "+216",
            display: "+216 (Tunisia)",
            countryName: "Tunisia",
          },
          {
            id: 220,
            flag: "https://flagcdn.com/w20/tr.png",
            code: "+90",
            display: "+90 (Turkey)",
            countryName: "Turkey",
          },
          {
            id: 221,
            flag: "https://flagcdn.com/w20/tm.png",
            code: "+993",
            display: "+993 (Turkmenistan)",
            countryName: "Turkmenistan",
          },
          {
            id: 222,
            flag: "https://flagcdn.com/w20/tc.png",
            code: "+1649",
            display: "+1649 (Turks and Caicos Islands)",
            countryName: "Turks and Caicos Islands",
          },
          {
            id: 223,
            flag: "https://flagcdn.com/w20/tv.png",
            code: "+688",
            display: "+688 (Tuvalu)",
            countryName: "Tuvalu",
          },
          {
            id: 224,
            flag: "https://flagcdn.com/w20/vi.png",
            code: "+1340",
            display: "+1340 (U.S. Virgin Islands)",
            countryName: "U.S. Virgin Islands",
          },
          {
            id: 225,
            flag: "https://flagcdn.com/w20/ug.png",
            code: "+256",
            display: "+256 (Uganda)",
            countryName: "Uganda",
          },
          {
            id: 226,
            flag: "https://flagcdn.com/w20/ua.png",
            code: "+380",
            display: "+380 (Ukraine)",
            countryName: "Ukraine",
          },
          {
            id: 227,
            flag: "https://flagcdn.com/w20/ae.png",
            code: "+971",
            display: "+971 (United Arab Emirates)",
            countryName: "United Arab Emirates",
          },
          {
            id: 228,
            flag: "https://flagcdn.com/w20/gb.png",
            code: "+44",
            display: "+44 (United Kingdom)",
            countryName: "United Kingdom",
          },
          {
            id: 229,
            flag: "https://flagcdn.com/w20/us.png",
            code: "+1",
            display: "+1 (United States)",
            countryName: "United States",
          },
          {
            id: 230,
            flag: "https://flagcdn.com/w20/uy.png",
            code: "+598",
            display: "+598 (Uruguay)",
            countryName: "Uruguay",
          },
          {
            id: 231,
            flag: "https://flagcdn.com/w20/uz.png",
            code: "+998",
            display: "+998 (Uzbekistan)",
            countryName: "Uzbekistan",
          },
          {
            id: 232,
            flag: "https://flagcdn.com/w20/vu.png",
            code: "+678",
            display: "+678 (Vanuatu)",
            countryName: "Vanuatu",
          },
          {
            id: 233,
            flag: "https://flagcdn.com/w20/va.png",
            code: "+379",
            display: "+379 (Vatican)",
            countryName: "Vatican",
          },
          {
            id: 234,
            flag: "https://flagcdn.com/w20/ve.png",
            code: "+58",
            display: "+58 (Venezuela)",
            countryName: "Venezuela",
          },
          {
            id: 235,
            flag: "https://flagcdn.com/w20/vn.png",
            code: "+84",
            display: "+84 (Vietnam)",
            countryName: "Vietnam",
          },
          {
            id: 236,
            flag: "https://flagcdn.com/w20/wf.png",
            code: "+681",
            display: "+681 (Wallis and Futuna)",
            countryName: "Wallis and Futuna",
          },
          {
            id: 237,
            flag: "https://flagcdn.com/w20/eh.png",
            code: "+212",
            display: "+212 (Western Sahara)",
            countryName: "Western Sahara",
          },
          {
            id: 238,
            flag: "https://flagcdn.com/w20/ye.png",
            code: "+967",
            display: "+967 (Yemen)",
            countryName: "Yemen",
          },
          {
            id: 239,
            flag: "https://flagcdn.com/w20/zm.png",
            code: "+260",
            display: "+260 (Zambia)",
            countryName: "Zambia",
          },
          {
            id: 240,
            flag: "https://flagcdn.com/w20/zw.png",
            code: "+263",
            display: "+263 (Zimbabwe)",
            countryName: "Zimbabwe",
          },
        ],
      });
    });
  }

  getCurrencyCodeDetails() {
    return new Promise(function (resolve, reject) {
      resolve({
        status: 200,
        data: [
          { code: "AFN", text: "Afghanistan Afghanis – AFN" },
          { code: "ALL", text: "Albania Leke – ALL" },
          { code: "DZD", text: "Algeria Dinars – DZD" },
          { code: "ARS", text: "Argentina Pesos – ARS" },
          { code: "AUD", text: "Australia Dollars – AUD" },
          { code: "ATS", text: "Austria Schillings – ATS" },
          { code: "BSD", text: "Bahamas Dollars – BSD" },
          { code: "BHD", text: "Bahrain Dinars – BHD" },
          { code: "BDT", text: "Bangladesh Taka – BDT" },
          { code: "BBD", text: "Barbados Dollars – BBD" },
          { code: "BEF", text: "Belgium Francs – BEF" },
          { code: "BMD", text: "Bermuda Dollars – BMD" },
          { code: "BRL", text: "Brazil Reais – BRL" },
          { code: "BGN", text: "Bulgaria Leva – BGN" },
          { code: "CAD", text: "Canada Dollars – CAD" },
          { code: "XOF", text: "CFA BCEAO Francs – XOF" },
          { code: "XAF", text: "CFA BEAC Francs – XAF" },
          { code: "CLP", text: "Chile Pesos – CLP" },
          { code: "CNY", text: "China Yuan Renminbi – CNY" },
          { code: "COP", text: "Colombia Pesos – COP" },
          { code: "XPF", text: "CFP Francs – XPF" },
          { code: "CRC", text: "Costa Rica Colones – CRC" },
          { code: "HRK", text: "Croatia Kuna – HRK" },
          { code: "CYP", text: "Cyprus Pounds – CYP" },
          { code: "CZK", text: "Czech Republic Koruny – CZK" },
          { code: "DKK", text: "Denmark Kroner – DKK" },
          { code: "DEM", text: "Deutsche (Germany) Marks – DEM" },
          { code: "DOP", text: "Dominican Republic Pesos – DOP" },
          { code: "NLG", text: "Dutch (Netherlands) Guilders - NLG" },
          { code: "XCD", text: "Eastern Caribbean Dollars – XCD" },
          { code: "EGP", text: "Egypt Pounds – EGP" },
          { code: "EEK", text: "Estonia Krooni – EEK" },
          { code: "EUR", text: "Euro – EUR" },
          { code: "FJD", text: "Fiji Dollars – FJD" },
          { code: "FIM", text: "Finland Markkaa – FIM" },
          { code: "FRF", text: "France Francs – FRF" },
          { code: "DEM", text: "Germany Deutsche Marks – DEM" },
          { code: "XAU", text: "Gold Ounces – XAU" },
          { code: "GRD", text: "Greece Drachmae – GRD" },
          { code: "GTQ", text: "Guatemalan Quetzal – GTQ" },
          { code: "NLG", text: "Holland (Netherlands) Guilders – NLG" },
          { code: "HKD", text: "Hong Kong Dollars – HKD" },
          { code: "HUF", text: "Hungary Forint – HUF" },
          { code: "ISK", text: "Iceland Kronur – ISK" },
          { code: "XDR", text: "IMF Special Drawing Right – XDR" },
          { code: "INR", text: "India Rupees – INR" },
          { code: "IDR", text: "Indonesia Rupiahs – IDR" },
          { code: "IRR", text: "Iran Rials – IRR" },
          { code: "IQD", text: "Iraq Dinars – IQD" },
          { code: "IEP", text: "Ireland Pounds – IEP" },
          { code: "ILS", text: "Israel New Shekels – ILS" },
          { code: "ITL", text: "Italy Lire – ITL" },
          { code: "JMD", text: "Jamaica Dollars – JMD" },
          { code: "JPY", text: "Japan Yen – JPY" },
          { code: "JOD", text: "Jordan Dinars – JOD" },
          { code: "KES", text: "Kenya Shillings – KES" },
          { code: "KRW", text: "Korea (South) Won – KRW" },
          { code: "KWD", text: "Kuwait Dinars – KWD" },
          { code: "LBP", text: "Lebanon Pounds – LBP" },
          { code: "LUF", text: "Luxembourg Francs – LUF" },
          { code: "MYR", text: "Malaysia Ringgits – MYR" },
          { code: "MTL", text: "Malta Liri – MTL" },
          { code: "MUR", text: "Mauritius Rupees – MUR" },
          { code: "MXN", text: "Mexico Pesos – MXN" },
          { code: "MAD", text: "Morocco Dirhams – MAD" },
          { code: "NLG", text: "Netherlands Guilders – NLG" },
          { code: "NZD", text: "New Zealand Dollars – NZD" },
          { code: "NOK", text: "Norway Kroner – NOK" },
          { code: "OMR", text: "Oman Rials – OMR" },
          { code: "PKR", text: "Pakistan Rupees – PKR" },
          { code: "XPD", text: "Palladium Ounces – XPD" },
          { code: "PEN", text: "Peru Nuevos Soles – PEN" },
          { code: "PHP", text: "Philippines Pesos – PHP" },
          { code: "XPT", text: "Platinum Ounces – XPT" },
          { code: "PLN", text: "Poland Zlotych – PLN" },
          { code: "PTE", text: "Portugal Escudos – PTE" },
          { code: "QAR", text: "Qatar Riyals – QAR" },
          { code: "RON", text: "Romania New Lei – RON" },
          { code: "ROL", text: "Romania Lei – ROL" },
          { code: "RUB", text: "Russia Rubles – RUB" },
          { code: "SAR", text: "Saudi Arabia Riyals – SAR" },
          { code: "XAG", text: "Silver Ounces – XAG" },
          { code: "SGD", text: "Singapore Dollars – SGD" },
          { code: "SKK", text: "Slovakia Koruny – SKK" },
          { code: "SIT", text: "Slovenia Tolars – SIT" },
          { code: "ZAR", text: "South Africa Rand – ZAR" },
          { code: "KRW", text: "South Korea Won – KRW" },
          { code: "ESP", text: "Spain Pesetas – ESP" },
          { code: "XDR", text: "Special Drawing Rights (IMF) – XDR" },
          { code: "LKR", text: "Sri Lanka Rupees – LKR" },
          { code: "SDD", text: "Sudan Dinars – SDD" },
          { code: "SEK", text: "Sweden Kronor – SEK" },
          { code: "CHF", text: "Switzerland Francs – CHF" },
          { code: "TWD", text: "Taiwan New Dollars – TWD" },
          { code: "THB", text: "Thailand Baht – THB" },
          { code: "TTD", text: "Trinidad and Tobago Dollars – TTD" },
          { code: "TND", text: "Tunisia Dinars – TND" },
          { code: "TRY", text: "Turkey New Lira – TRY" },
          { code: "AED", text: "United Arab Emirates Dirhams – AED" },
          { code: "GBP", text: "United Kingdom Pounds – GBP" },
          { code: "USD", text: "United States Dollars – USD" },
          { code: "VEB", text: "Venezuela Bolivares – VEB" },
          { code: "VND", text: "Vietnam Dong – VND" },
          { code: "ZMK", text: "Zambia Kwacha – ZMK" },
        ],
      });
    });
  }

  getNivoLineChartData(data?: any) {
    return new Promise(function (resolve, reject) {
      resolve({
        status: 200,
        data: data ?? nivoLineChartData2,
      });
    });
  }

  getNivoPieChartData(data?: any) {
    return new Promise(function (resolve, reject) {
      resolve({
        status: 200,
        data: data ?? nivoPieChartData,
      });
    });
  }
  getChatDiagramData(data?: any) {
    return new Promise(function (resolve, reject) {
      resolve({
        status: 200,
        data: data ?? scenario1DiagramData,
      });
    });
  }
}

export default new StaticDataService();
