export const CURRENCY_CODE = [
  {
    Country: "AFGHANISTAN",
    Currency: "Afghani",
    "Alphabetic Code": "AFN",
    "Numeric Code": 971,
    "Minor Unit": 2,
  },
  {
    Country: "ÅLAND ISLANDS",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "ALBANIA",
    Currency: "Lek",
    "Alphabetic Code": "ALL",
    "Numeric Code": 8,
    "Minor Unit": 2,
  },
  {
    Country: "ALGERIA",
    Currency: "Algerian Dinar",
    "Alphabetic Code": "DZD",
    "Numeric Code": 12,
    "Minor Unit": 2,
  },
  {
    Country: "AMERICAN SAMOA",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "ANDORRA",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "ANGOLA",
    Currency: "Kwanza",
    "Alphabetic Code": "AOA",
    "Numeric Code": 973,
    "Minor Unit": 2,
  },
  {
    Country: "ANGUILLA",
    Currency: "East Caribbean Dollar",
    "Alphabetic Code": "XCD",
    "Numeric Code": 951,
    "Minor Unit": 2,
  },
  {
    Country: "ANTARCTICA",
    Currency: "No universal currency",
    "Alphabetic Code": "",
    "Numeric Code": "",
    "Minor Unit": "",
  },
  {
    Country: "ANTIGUA AND BARBUDA",
    Currency: "East Caribbean Dollar",
    "Alphabetic Code": "XCD",
    "Numeric Code": 951,
    "Minor Unit": 2,
  },
  {
    Country: "ARGENTINA",
    Currency: "Argentine Peso",
    "Alphabetic Code": "ARS",
    "Numeric Code": 32,
    "Minor Unit": 2,
  },
  {
    Country: "ARMENIA",
    Currency: "Armenian Dram",
    "Alphabetic Code": "AMD",
    "Numeric Code": 51,
    "Minor Unit": 2,
  },
  {
    Country: "ARUBA",
    Currency: "Aruban Florin",
    "Alphabetic Code": "AWG",
    "Numeric Code": 533,
    "Minor Unit": 2,
  },
  {
    Country: "AUSTRALIA",
    Currency: "Australian Dollar",
    "Alphabetic Code": "AUD",
    "Numeric Code": 36,
    "Minor Unit": 2,
  },
  {
    Country: "AUSTRIA",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "AZERBAIJAN",
    Currency: "Azerbaijan Manat",
    "Alphabetic Code": "AZN",
    "Numeric Code": 944,
    "Minor Unit": 2,
  },
  {
    Country: "BAHAMAS (THE)",
    Currency: "Bahamian Dollar",
    "Alphabetic Code": "BSD",
    "Numeric Code": 44,
    "Minor Unit": 2,
  },
  {
    Country: "BAHRAIN",
    Currency: "Bahraini Dinar",
    "Alphabetic Code": "BHD",
    "Numeric Code": 48,
    "Minor Unit": 3,
  },
  {
    Country: "BANGLADESH",
    Currency: "Taka",
    "Alphabetic Code": "BDT",
    "Numeric Code": 50,
    "Minor Unit": 2,
  },
  {
    Country: "BARBADOS",
    Currency: "Barbados Dollar",
    "Alphabetic Code": "BBD",
    "Numeric Code": 52,
    "Minor Unit": 2,
  },
  {
    Country: "BELARUS",
    Currency: "Belarusian Ruble",
    "Alphabetic Code": "BYN",
    "Numeric Code": 933,
    "Minor Unit": 2,
  },
  {
    Country: "BELGIUM",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "BELIZE",
    Currency: "Belize Dollar",
    "Alphabetic Code": "BZD",
    "Numeric Code": 84,
    "Minor Unit": 2,
  },
  {
    Country: "BENIN",
    Currency: "CFA Franc BCEAO",
    "Alphabetic Code": "XOF",
    "Numeric Code": 952,
    "Minor Unit": 0,
  },
  {
    Country: "BERMUDA",
    Currency: "Bermudian Dollar",
    "Alphabetic Code": "BMD",
    "Numeric Code": 60,
    "Minor Unit": 2,
  },
  {
    Country: "BHUTAN",
    Currency: "Indian Rupee",
    "Alphabetic Code": "INR",
    "Numeric Code": 356,
    "Minor Unit": 2,
  },
  {
    Country: "BHUTAN",
    Currency: "Ngultrum",
    "Alphabetic Code": "BTN",
    "Numeric Code": 64,
    "Minor Unit": 2,
  },
  {
    Country: "BOLIVIA (PLURINATIONAL STATE OF)",
    Currency: "Boliviano",
    "Alphabetic Code": "BOB",
    "Numeric Code": 68,
    "Minor Unit": 2,
  },
  {
    Country: "BOLIVIA (PLURINATIONAL STATE OF)",
    Currency: "Mvdol",
    "Alphabetic Code": "BOV",
    "Numeric Code": 984,
    "Minor Unit": 2,
  },
  {
    Country: "BONAIRE, SINT EUSTATIUS AND SABA",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "BOSNIA AND HERZEGOVINA",
    Currency: "Convertible Mark",
    "Alphabetic Code": "BAM",
    "Numeric Code": 977,
    "Minor Unit": 2,
  },
  {
    Country: "BOTSWANA",
    Currency: "Pula",
    "Alphabetic Code": "BWP",
    "Numeric Code": 72,
    "Minor Unit": 2,
  },
  {
    Country: "BOUVET ISLAND",
    Currency: "Norwegian Krone",
    "Alphabetic Code": "NOK",
    "Numeric Code": 578,
    "Minor Unit": 2,
  },
  {
    Country: "BRAZIL",
    Currency: "Brazilian Real",
    "Alphabetic Code": "BRL",
    "Numeric Code": 986,
    "Minor Unit": 2,
  },
  {
    Country: "BRITISH INDIAN OCEAN TERRITORY (THE)",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "BRUNEI DARUSSALAM",
    Currency: "Brunei Dollar",
    "Alphabetic Code": "BND",
    "Numeric Code": 96,
    "Minor Unit": 2,
  },
  {
    Country: "BULGARIA",
    Currency: "Bulgarian Lev",
    "Alphabetic Code": "BGN",
    "Numeric Code": 975,
    "Minor Unit": 2,
  },
  {
    Country: "BURKINA FASO",
    Currency: "CFA Franc BCEAO",
    "Alphabetic Code": "XOF",
    "Numeric Code": 952,
    "Minor Unit": 0,
  },
  {
    Country: "BURUNDI",
    Currency: "Burundi Franc",
    "Alphabetic Code": "BIF",
    "Numeric Code": 108,
    "Minor Unit": 0,
  },
  {
    Country: "CABO VERDE",
    Currency: "Cabo Verde Escudo",
    "Alphabetic Code": "CVE",
    "Numeric Code": 132,
    "Minor Unit": 2,
  },
  {
    Country: "CAMBODIA",
    Currency: "Riel",
    "Alphabetic Code": "KHR",
    "Numeric Code": 116,
    "Minor Unit": 2,
  },
  {
    Country: "CAMEROON",
    Currency: "CFA Franc BEAC",
    "Alphabetic Code": "XAF",
    "Numeric Code": 950,
    "Minor Unit": 0,
  },
  {
    Country: "CANADA",
    Currency: "Canadian Dollar",
    "Alphabetic Code": "CAD",
    "Numeric Code": 124,
    "Minor Unit": 2,
  },
  {
    Country: "CAYMAN ISLANDS (THE)",
    Currency: "Cayman Islands Dollar",
    "Alphabetic Code": "KYD",
    "Numeric Code": 136,
    "Minor Unit": 2,
  },
  {
    Country: "CENTRAL AFRICAN REPUBLIC (THE)",
    Currency: "CFA Franc BEAC",
    "Alphabetic Code": "XAF",
    "Numeric Code": 950,
    "Minor Unit": 0,
  },
  {
    Country: "CHAD",
    Currency: "CFA Franc BEAC",
    "Alphabetic Code": "XAF",
    "Numeric Code": 950,
    "Minor Unit": 0,
  },
  {
    Country: "CHILE",
    Currency: "Chilean Peso",
    "Alphabetic Code": "CLP",
    "Numeric Code": 152,
    "Minor Unit": 0,
  },
  {
    Country: "CHILE",
    Currency: "Unidad de Fomento",
    "Alphabetic Code": "CLF",
    "Numeric Code": 990,
    "Minor Unit": 4,
  },
  {
    Country: "CHINA",
    Currency: "Yuan Renminbi",
    "Alphabetic Code": "CNY",
    "Numeric Code": 156,
    "Minor Unit": 2,
  },
  {
    Country: "CHRISTMAS ISLAND",
    Currency: "Australian Dollar",
    "Alphabetic Code": "AUD",
    "Numeric Code": 36,
    "Minor Unit": 2,
  },
  {
    Country: "COCOS (KEELING) ISLANDS (THE)",
    Currency: "Australian Dollar",
    "Alphabetic Code": "AUD",
    "Numeric Code": 36,
    "Minor Unit": 2,
  },
  {
    Country: "COLOMBIA",
    Currency: "Colombian Peso",
    "Alphabetic Code": "COP",
    "Numeric Code": 170,
    "Minor Unit": 2,
  },
  {
    Country: "COLOMBIA",
    Currency: "Unidad de Valor Real",
    "Alphabetic Code": "COU",
    "Numeric Code": 970,
    "Minor Unit": 2,
  },
  {
    Country: "COMOROS (THE)",
    Currency: "Comorian Franc",
    "Alphabetic Code": "KMF",
    "Numeric Code": 174,
    "Minor Unit": 0,
  },
  {
    Country: "CONGO (THE DEMOCRATIC REPUBLIC OF THE)",
    Currency: "Congolese Franc",
    "Alphabetic Code": "CDF",
    "Numeric Code": 976,
    "Minor Unit": 2,
  },
  {
    Country: "CONGO (THE)",
    Currency: "CFA Franc BEAC",
    "Alphabetic Code": "XAF",
    "Numeric Code": 950,
    "Minor Unit": 0,
  },
  {
    Country: "COOK ISLANDS (THE)",
    Currency: "New Zealand Dollar",
    "Alphabetic Code": "NZD",
    "Numeric Code": 554,
    "Minor Unit": 2,
  },
  {
    Country: "COSTA RICA",
    Currency: "Costa Rican Colon",
    "Alphabetic Code": "CRC",
    "Numeric Code": 188,
    "Minor Unit": 2,
  },
  {
    Country: "CÔTE D'IVOIRE",
    Currency: "CFA Franc BCEAO",
    "Alphabetic Code": "XOF",
    "Numeric Code": 952,
    "Minor Unit": 0,
  },
  {
    Country: "CROATIA",
    Currency: "Kuna",
    "Alphabetic Code": "HRK",
    "Numeric Code": 191,
    "Minor Unit": 2,
  },
  {
    Country: "CUBA",
    Currency: "Cuban Peso",
    "Alphabetic Code": "CUP",
    "Numeric Code": 192,
    "Minor Unit": 2,
  },
  {
    Country: "CUBA",
    Currency: "Peso Convertible",
    "Alphabetic Code": "CUC",
    "Numeric Code": 931,
    "Minor Unit": 2,
  },
  {
    Country: "CURAÇAO",
    Currency: "Netherlands Antillean Guilder",
    "Alphabetic Code": "ANG",
    "Numeric Code": 532,
    "Minor Unit": 2,
  },
  {
    Country: "CYPRUS",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "CZECHIA",
    Currency: "Czech Koruna",
    "Alphabetic Code": "CZK",
    "Numeric Code": 203,
    "Minor Unit": 2,
  },
  {
    Country: "DENMARK",
    Currency: "Danish Krone",
    "Alphabetic Code": "DKK",
    "Numeric Code": 208,
    "Minor Unit": 2,
  },
  {
    Country: "DJIBOUTI",
    Currency: "Djibouti Franc",
    "Alphabetic Code": "DJF",
    "Numeric Code": 262,
    "Minor Unit": 0,
  },
  {
    Country: "DOMINICA",
    Currency: "East Caribbean Dollar",
    "Alphabetic Code": "XCD",
    "Numeric Code": 951,
    "Minor Unit": 2,
  },
  {
    Country: "DOMINICAN REPUBLIC (THE)",
    Currency: "Dominican Peso",
    "Alphabetic Code": "DOP",
    "Numeric Code": 214,
    "Minor Unit": 2,
  },
  {
    Country: "ECUADOR",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "EGYPT",
    Currency: "Egyptian Pound",
    "Alphabetic Code": "EGP",
    "Numeric Code": 818,
    "Minor Unit": 2,
  },
  {
    Country: "EL SALVADOR",
    Currency: "El Salvador Colon",
    "Alphabetic Code": "SVC",
    "Numeric Code": 222,
    "Minor Unit": 2,
  },
  {
    Country: "EL SALVADOR",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "EQUATORIAL GUINEA",
    Currency: "CFA Franc BEAC",
    "Alphabetic Code": "XAF",
    "Numeric Code": 950,
    "Minor Unit": 0,
  },
  {
    Country: "ERITREA",
    Currency: "Nakfa",
    "Alphabetic Code": "ERN",
    "Numeric Code": 232,
    "Minor Unit": 2,
  },
  {
    Country: "ESTONIA",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "ETHIOPIA",
    Currency: "Ethiopian Birr",
    "Alphabetic Code": "ETB",
    "Numeric Code": 230,
    "Minor Unit": 2,
  },
  {
    Country: "EUROPEAN UNION",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "FALKLAND ISLANDS (THE) [MALVINAS]",
    Currency: "Falkland Islands Pound",
    "Alphabetic Code": "FKP",
    "Numeric Code": 238,
    "Minor Unit": 2,
  },
  {
    Country: "FAROE ISLANDS (THE)",
    Currency: "Danish Krone",
    "Alphabetic Code": "DKK",
    "Numeric Code": 208,
    "Minor Unit": 2,
  },
  {
    Country: "FIJI",
    Currency: "Fiji Dollar",
    "Alphabetic Code": "FJD",
    "Numeric Code": 242,
    "Minor Unit": 2,
  },
  {
    Country: "FINLAND",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "FRANCE",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "FRENCH GUIANA",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "FRENCH POLYNESIA",
    Currency: "CFP Franc",
    "Alphabetic Code": "XPF",
    "Numeric Code": 953,
    "Minor Unit": 0,
  },
  {
    Country: "FRENCH SOUTHERN TERRITORIES (THE)",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "GABON",
    Currency: "CFA Franc BEAC",
    "Alphabetic Code": "XAF",
    "Numeric Code": 950,
    "Minor Unit": 0,
  },
  {
    Country: "GAMBIA (THE)",
    Currency: "Dalasi",
    "Alphabetic Code": "GMD",
    "Numeric Code": 270,
    "Minor Unit": 2,
  },
  {
    Country: "GEORGIA",
    Currency: "Lari",
    "Alphabetic Code": "GEL",
    "Numeric Code": 981,
    "Minor Unit": 2,
  },
  {
    Country: "GERMANY",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "GHANA",
    Currency: "Ghana Cedi",
    "Alphabetic Code": "GHS",
    "Numeric Code": 936,
    "Minor Unit": 2,
  },
  {
    Country: "GIBRALTAR",
    Currency: "Gibraltar Pound",
    "Alphabetic Code": "GIP",
    "Numeric Code": 292,
    "Minor Unit": 2,
  },
  {
    Country: "GREECE",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "GREENLAND",
    Currency: "Danish Krone",
    "Alphabetic Code": "DKK",
    "Numeric Code": 208,
    "Minor Unit": 2,
  },
  {
    Country: "GRENADA",
    Currency: "East Caribbean Dollar",
    "Alphabetic Code": "XCD",
    "Numeric Code": 951,
    "Minor Unit": 2,
  },
  {
    Country: "GUADELOUPE",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "GUAM",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "GUATEMALA",
    Currency: "Quetzal",
    "Alphabetic Code": "GTQ",
    "Numeric Code": 320,
    "Minor Unit": 2,
  },
  {
    Country: "GUERNSEY",
    Currency: "Pound Sterling",
    "Alphabetic Code": "GBP",
    "Numeric Code": 826,
    "Minor Unit": 2,
  },
  {
    Country: "GUINEA",
    Currency: "Guinean Franc",
    "Alphabetic Code": "GNF",
    "Numeric Code": 324,
    "Minor Unit": 0,
  },
  {
    Country: "GUINEA-BISSAU",
    Currency: "CFA Franc BCEAO",
    "Alphabetic Code": "XOF",
    "Numeric Code": 952,
    "Minor Unit": 0,
  },
  {
    Country: "GUYANA",
    Currency: "Guyana Dollar",
    "Alphabetic Code": "GYD",
    "Numeric Code": 328,
    "Minor Unit": 2,
  },
  {
    Country: "HAITI",
    Currency: "Gourde",
    "Alphabetic Code": "HTG",
    "Numeric Code": 332,
    "Minor Unit": 2,
  },
  {
    Country: "HAITI",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "HEARD ISLAND AND McDONALD ISLANDS",
    Currency: "Australian Dollar",
    "Alphabetic Code": "AUD",
    "Numeric Code": 36,
    "Minor Unit": 2,
  },
  {
    Country: "HOLY SEE (THE)",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "HONDURAS",
    Currency: "Lempira",
    "Alphabetic Code": "HNL",
    "Numeric Code": 340,
    "Minor Unit": 2,
  },
  {
    Country: "HONG KONG",
    Currency: "Hong Kong Dollar",
    "Alphabetic Code": "HKD",
    "Numeric Code": 344,
    "Minor Unit": 2,
  },
  {
    Country: "HUNGARY",
    Currency: "Forint",
    "Alphabetic Code": "HUF",
    "Numeric Code": 348,
    "Minor Unit": 2,
  },
  {
    Country: "ICELAND",
    Currency: "Iceland Krona",
    "Alphabetic Code": "ISK",
    "Numeric Code": 352,
    "Minor Unit": 0,
  },
  {
    Country: "INDIA",
    Currency: "Indian Rupee",
    "Alphabetic Code": "INR",
    "Numeric Code": 356,
    "Minor Unit": 2,
  },
  {
    Country: "INDONESIA",
    Currency: "Rupiah",
    "Alphabetic Code": "IDR",
    "Numeric Code": 360,
    "Minor Unit": 2,
  },
  {
    Country: "INTERNATIONAL MONETARY FUND (IMF)",
    Currency: "SDR (Special Drawing Right)",
    "Alphabetic Code": "XDR",
    "Numeric Code": 960,
    "Minor Unit": "NA",
  },
  {
    Country: "IRAN (ISLAMIC REPUBLIC OF)",
    Currency: "Iranian Rial",
    "Alphabetic Code": "IRR",
    "Numeric Code": 364,
    "Minor Unit": 2,
  },
  {
    Country: "IRAQ",
    Currency: "Iraqi Dinar",
    "Alphabetic Code": "IQD",
    "Numeric Code": 368,
    "Minor Unit": 3,
  },
  {
    Country: "IRELAND",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "ISLE OF MAN",
    Currency: "Pound Sterling",
    "Alphabetic Code": "GBP",
    "Numeric Code": 826,
    "Minor Unit": 2,
  },
  {
    Country: "ISRAEL",
    Currency: "New Israeli Sheqel",
    "Alphabetic Code": "ILS",
    "Numeric Code": 376,
    "Minor Unit": 2,
  },
  {
    Country: "ITALY",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "JAMAICA",
    Currency: "Jamaican Dollar",
    "Alphabetic Code": "JMD",
    "Numeric Code": 388,
    "Minor Unit": 2,
  },
  {
    Country: "JAPAN",
    Currency: "Yen",
    "Alphabetic Code": "JPY",
    "Numeric Code": 392,
    "Minor Unit": 0,
  },
  {
    Country: "JERSEY",
    Currency: "Pound Sterling",
    "Alphabetic Code": "GBP",
    "Numeric Code": 826,
    "Minor Unit": 2,
  },
  {
    Country: "JORDAN",
    Currency: "Jordanian Dinar",
    "Alphabetic Code": "JOD",
    "Numeric Code": 400,
    "Minor Unit": 3,
  },
  {
    Country: "KAZAKHSTAN",
    Currency: "Tenge",
    "Alphabetic Code": "KZT",
    "Numeric Code": 398,
    "Minor Unit": 2,
  },
  {
    Country: "KENYA",
    Currency: "Kenyan Shilling",
    "Alphabetic Code": "KES",
    "Numeric Code": 404,
    "Minor Unit": 2,
  },
  {
    Country: "KIRIBATI",
    Currency: "Australian Dollar",
    "Alphabetic Code": "AUD",
    "Numeric Code": 36,
    "Minor Unit": 2,
  },
  {
    Country: "KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)",
    Currency: "North Korean Won",
    "Alphabetic Code": "KPW",
    "Numeric Code": 408,
    "Minor Unit": 2,
  },
  {
    Country: "KOREA (THE REPUBLIC OF)",
    Currency: "Won",
    "Alphabetic Code": "KRW",
    "Numeric Code": 410,
    "Minor Unit": 0,
  },
  {
    Country: "KUWAIT",
    Currency: "Kuwaiti Dinar",
    "Alphabetic Code": "KWD",
    "Numeric Code": 414,
    "Minor Unit": 3,
  },
  {
    Country: "KYRGYZSTAN",
    Currency: "Som",
    "Alphabetic Code": "KGS",
    "Numeric Code": 417,
    "Minor Unit": 2,
  },
  {
    Country: "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
    Currency: "Lao Kip",
    "Alphabetic Code": "LAK",
    "Numeric Code": 418,
    "Minor Unit": 2,
  },
  {
    Country: "LATVIA",
    Currency: "UR",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "LEBANON",
    Currency: "Lebanese Pound",
    "Alphabetic Code": "LBP",
    "Numeric Code": 422,
    "Minor Unit": 2,
  },
  {
    Country: "LESOTHO",
    Currency: "Loti",
    "Alphabetic Code": "LSL",
    "Numeric Code": 426,
    "Minor Unit": 2,
  },
  {
    Country: "LESOTHO",
    Currency: "Rand",
    "Alphabetic Code": "ZAR",
    "Numeric Code": 710,
    "Minor Unit": 2,
  },
  {
    Country: "LIBERIA",
    Currency: "Liberian Dollar",
    "Alphabetic Code": "LRD",
    "Numeric Code": 430,
    "Minor Unit": 2,
  },
  {
    Country: "LIBYA",
    Currency: "Libyan Dinar",
    "Alphabetic Code": "LYD",
    "Numeric Code": 434,
    "Minor Unit": 3,
  },
  {
    Country: "LIECHTENSTEIN",
    Currency: "Swiss Franc",
    "Alphabetic Code": "CHF",
    "Numeric Code": 756,
    "Minor Unit": 2,
  },
  {
    Country: "LITHUANIA",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "LUXEMBOURG",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "MACAO",
    Currency: "Pataca",
    "Alphabetic Code": "MOP",
    "Numeric Code": 446,
    "Minor Unit": 2,
  },
  {
    Country: "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)",
    Currency: "Denar",
    "Alphabetic Code": "MKD",
    "Numeric Code": 807,
    "Minor Unit": 2,
  },
  {
    Country: "MADAGASCAR",
    Currency: "Malagasy Ariary",
    "Alphabetic Code": "MGA",
    "Numeric Code": 969,
    "Minor Unit": 2,
  },
  {
    Country: "MALAWI",
    Currency: "Malawi Kwacha",
    "Alphabetic Code": "MWK",
    "Numeric Code": 454,
    "Minor Unit": 2,
  },
  {
    Country: "MALAYSIA",
    Currency: "Malaysian Ringgit",
    "Alphabetic Code": "MYR",
    "Numeric Code": 458,
    "Minor Unit": 2,
  },
  {
    Country: "MALDIVES",
    Currency: "Rufiyaa",
    "Alphabetic Code": "MVR",
    "Numeric Code": 462,
    "Minor Unit": 2,
  },
  {
    Country: "MALI",
    Currency: "CFA Franc BCEAO",
    "Alphabetic Code": "XOF",
    "Numeric Code": 952,
    "Minor Unit": 0,
  },
  {
    Country: "MALTA",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "MARSHALL ISLANDS (THE)",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "MARTINIQUE",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "MAURITANIA",
    Currency: "Ouguiya",
    "Alphabetic Code": "MRU",
    "Numeric Code": 929,
    "Minor Unit": 2,
  },
  {
    Country: "MAURITIUS",
    Currency: "Mauritius Rupee",
    "Alphabetic Code": "MUR",
    "Numeric Code": 480,
    "Minor Unit": 2,
  },
  {
    Country: "MAYOTTE",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP",
    Currency: "ADB Unit of Account",
    "Alphabetic Code": "XUA",
    "Numeric Code": 965,
    "Minor Unit": "NA",
  },
  {
    Country: "MEXICO",
    Currency: "Mexican Peso",
    "Alphabetic Code": "MXN",
    "Numeric Code": 484,
    "Minor Unit": 2,
  },
  {
    Country: "MEXICO",
    Currency: "Mexican Unidad de Inversion (UDI)",
    "Alphabetic Code": "MXV",
    "Numeric Code": 979,
    "Minor Unit": 2,
  },
  {
    Country: "MICRONESIA (FEDERATED STATES OF)",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "MOLDOVA (THE REPUBLIC OF)",
    Currency: "Moldovan Leu",
    "Alphabetic Code": "MDL",
    "Numeric Code": 498,
    "Minor Unit": 2,
  },
  {
    Country: "MONACO",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "MONGOLIA",
    Currency: "Tugrik",
    "Alphabetic Code": "MNT",
    "Numeric Code": 496,
    "Minor Unit": 2,
  },
  {
    Country: "MONTENEGRO",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "MONTSERRAT",
    Currency: "East Caribbean Dollar",
    "Alphabetic Code": "XCD",
    "Numeric Code": 951,
    "Minor Unit": 2,
  },
  {
    Country: "MOROCCO",
    Currency: "Moroccan Dirham",
    "Alphabetic Code": "MAD",
    "Numeric Code": 504,
    "Minor Unit": 2,
  },
  {
    Country: "MOZAMBIQUE",
    Currency: "Mozambique Metical",
    "Alphabetic Code": "MZN",
    "Numeric Code": 943,
    "Minor Unit": 2,
  },
  {
    Country: "MYANMAR",
    Currency: "Kyat",
    "Alphabetic Code": "MMK",
    "Numeric Code": 104,
    "Minor Unit": 2,
  },
  {
    Country: "NAMIBIA",
    Currency: "Namibia Dollar",
    "Alphabetic Code": "NAD",
    "Numeric Code": 516,
    "Minor Unit": 2,
  },
  {
    Country: "NAMIBIA",
    Currency: "Rand",
    "Alphabetic Code": "ZAR",
    "Numeric Code": 710,
    "Minor Unit": 2,
  },
  {
    Country: "NAURU",
    Currency: "Australian Dollar",
    "Alphabetic Code": "AUD",
    "Numeric Code": 36,
    "Minor Unit": 2,
  },
  {
    Country: "NEPAL",
    Currency: "Nepalese Rupee",
    "Alphabetic Code": "NPR",
    "Numeric Code": 524,
    "Minor Unit": 2,
  },
  {
    Country: "NETHERLANDS (THE)",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "NEW CALEDONIA",
    Currency: "CFP Franc",
    "Alphabetic Code": "XPF",
    "Numeric Code": 953,
    "Minor Unit": 0,
  },
  {
    Country: "NEW ZEALAND",
    Currency: "New Zealand Dollar",
    "Alphabetic Code": "NZD",
    "Numeric Code": 554,
    "Minor Unit": 2,
  },
  {
    Country: "NICARAGUA",
    Currency: "Cordoba Oro",
    "Alphabetic Code": "NIO",
    "Numeric Code": 558,
    "Minor Unit": 2,
  },
  {
    Country: "NIGER (THE)",
    Currency: "CFA Franc BCEAO",
    "Alphabetic Code": "XOF",
    "Numeric Code": 952,
    "Minor Unit": 0,
  },
  {
    Country: "NIGERIA",
    Currency: "Naira",
    "Alphabetic Code": "NGN",
    "Numeric Code": 566,
    "Minor Unit": 2,
  },
  {
    Country: "NIUE",
    Currency: "New Zealand Dollar",
    "Alphabetic Code": "NZD",
    "Numeric Code": 554,
    "Minor Unit": 2,
  },
  {
    Country: "NORFOLK ISLAND",
    Currency: "Australian Dollar",
    "Alphabetic Code": "AUD",
    "Numeric Code": 36,
    "Minor Unit": 2,
  },
  {
    Country: "NORTHERN MARIANA ISLANDS (THE)",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "NORWAY",
    Currency: "Norwegian Krone",
    "Alphabetic Code": "NOK",
    "Numeric Code": 578,
    "Minor Unit": 2,
  },
  {
    Country: "OMAN",
    Currency: "Rial Omani",
    "Alphabetic Code": "OMR",
    "Numeric Code": 512,
    "Minor Unit": 3,
  },
  {
    Country: "PAKISTAN",
    Currency: "Pakistan Rupee",
    "Alphabetic Code": "PKR",
    "Numeric Code": 586,
    "Minor Unit": 2,
  },
  {
    Country: "PALAU",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "PALESTINE, STATE OF",
    Currency: "No universal currency",
    "Alphabetic Code": "",
    "Numeric Code": "",
    "Minor Unit": "",
  },
  {
    Country: "PANAMA",
    Currency: "Balboa",
    "Alphabetic Code": "PAB",
    "Numeric Code": 590,
    "Minor Unit": 2,
  },
  {
    Country: "PANAMA",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "PAPUA NEW GUINEA",
    Currency: "Kina",
    "Alphabetic Code": "PGK",
    "Numeric Code": 598,
    "Minor Unit": 2,
  },
  {
    Country: "PARAGUAY",
    Currency: "Guarani",
    "Alphabetic Code": "PYG",
    "Numeric Code": 600,
    "Minor Unit": 0,
  },
  {
    Country: "PERU",
    Currency: "Sol",
    "Alphabetic Code": "PEN",
    "Numeric Code": 604,
    "Minor Unit": 2,
  },
  {
    Country: "PHILIPPINES (THE)",
    Currency: "Philippine Peso",
    "Alphabetic Code": "PHP",
    "Numeric Code": 608,
    "Minor Unit": 2,
  },
  {
    Country: "PITCAIRN",
    Currency: "New Zealand Dollar",
    "Alphabetic Code": "NZD",
    "Numeric Code": 554,
    "Minor Unit": 2,
  },
  {
    Country: "POLAND",
    Currency: "Zloty",
    "Alphabetic Code": "PLN",
    "Numeric Code": 985,
    "Minor Unit": 2,
  },
  {
    Country: "PORTUGAL",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "PUERTO RICO",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "QATAR",
    Currency: "Qatari Rial",
    "Alphabetic Code": "QAR",
    "Numeric Code": 634,
    "Minor Unit": 2,
  },
  {
    Country: "RÉUNION",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "ROMANIA",
    Currency: "Romanian Leu",
    "Alphabetic Code": "RON",
    "Numeric Code": 946,
    "Minor Unit": 2,
  },
  {
    Country: "RUSSIAN FEDERATION (THE)",
    Currency: "Russian Ruble",
    "Alphabetic Code": "RUB",
    "Numeric Code": 643,
    "Minor Unit": 2,
  },
  {
    Country: "RWANDA",
    Currency: "Rwanda Franc",
    "Alphabetic Code": "RWF",
    "Numeric Code": 646,
    "Minor Unit": 0,
  },
  {
    Country: "SAINT BARTHÉLEMY",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
    Currency: "Saint Helena Pound",
    "Alphabetic Code": "SHP",
    "Numeric Code": 654,
    "Minor Unit": 2,
  },
  {
    Country: "SAINT KITTS AND NEVIS",
    Currency: "East Caribbean Dollar",
    "Alphabetic Code": "XCD",
    "Numeric Code": 951,
    "Minor Unit": 2,
  },
  {
    Country: "SAINT LUCIA",
    Currency: "East Caribbean Dollar",
    "Alphabetic Code": "XCD",
    "Numeric Code": 951,
    "Minor Unit": 2,
  },
  {
    Country: "SAINT MARTIN (FRENCH PART)",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "SAINT PIERRE AND MIQUELON",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "SAINT VINCENT AND THE GRENADINES",
    Currency: "East Caribbean Dollar",
    "Alphabetic Code": "XCD",
    "Numeric Code": 951,
    "Minor Unit": 2,
  },
  {
    Country: "SAMOA",
    Currency: "Tala",
    "Alphabetic Code": "WST",
    "Numeric Code": 882,
    "Minor Unit": 2,
  },
  {
    Country: "SAN MARINO",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "SAO TOME AND PRINCIPE",
    Currency: "Dobra",
    "Alphabetic Code": "STN",
    "Numeric Code": 930,
    "Minor Unit": 2,
  },
  {
    Country: "SAUDI ARABIA",
    Currency: "Saudi Riyal",
    "Alphabetic Code": "SAR",
    "Numeric Code": 682,
    "Minor Unit": 2,
  },
  {
    Country: "SENEGAL",
    Currency: "CFA Franc BCEAO",
    "Alphabetic Code": "XOF",
    "Numeric Code": 952,
    "Minor Unit": 0,
  },
  {
    Country: "SERBIA",
    Currency: "Serbian Dinar",
    "Alphabetic Code": "RSD",
    "Numeric Code": 941,
    "Minor Unit": 2,
  },
  {
    Country: "SEYCHELLES",
    Currency: "Seychelles Rupee",
    "Alphabetic Code": "SCR",
    "Numeric Code": 690,
    "Minor Unit": 2,
  },
  {
    Country: "SIERRA LEONE",
    Currency: "Leone",
    "Alphabetic Code": "SLL",
    "Numeric Code": 694,
    "Minor Unit": 2,
  },
  {
    Country: "SINGAPORE",
    Currency: "Singapore Dollar",
    "Alphabetic Code": "SGD",
    "Numeric Code": 702,
    "Minor Unit": 2,
  },
  {
    Country: "SINT MAARTEN (DUTCH PART)",
    Currency: "Netherlands Antillean Guilder",
    "Alphabetic Code": "ANG",
    "Numeric Code": 532,
    "Minor Unit": 2,
  },
  {
    Country: 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE',
    Currency: "Sucre",
    "Alphabetic Code": "XSU",
    "Numeric Code": 994,
    "Minor Unit": "NA",
  },
  {
    Country: "SLOVAKIA",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "SLOVENIA",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "SOLOMON ISLANDS",
    Currency: "Solomon Islands Dollar",
    "Alphabetic Code": "SBD",
    "Numeric Code": 90,
    "Minor Unit": 2,
  },
  {
    Country: "SOMALIA",
    Currency: "Somali Shilling",
    "Alphabetic Code": "SOS",
    "Numeric Code": 706,
    "Minor Unit": 2,
  },
  {
    Country: "SOUTH AFRICA",
    Currency: "Rand",
    "Alphabetic Code": "ZAR",
    "Numeric Code": 710,
    "Minor Unit": 2,
  },
  {
    Country: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    Currency: "No universal currency",
    "Alphabetic Code": "",
    "Numeric Code": "",
    "Minor Unit": "",
  },
  {
    Country: "SOUTH SUDAN",
    Currency: "South Sudanese Pound",
    "Alphabetic Code": "SSP",
    "Numeric Code": 728,
    "Minor Unit": 2,
  },
  {
    Country: "SPAIN",
    Currency: "Euro",
    "Alphabetic Code": "EUR",
    "Numeric Code": 978,
    "Minor Unit": 2,
  },
  {
    Country: "SRI LANKA",
    Currency: "Sri Lanka Rupee",
    "Alphabetic Code": "LKR",
    "Numeric Code": 144,
    "Minor Unit": 2,
  },
  {
    Country: "SUDAN (THE)",
    Currency: "Sudanese Pound",
    "Alphabetic Code": "SDG",
    "Numeric Code": 938,
    "Minor Unit": 2,
  },
  {
    Country: "SURINAME",
    Currency: "Surinam Dollar",
    "Alphabetic Code": "SRD",
    "Numeric Code": 968,
    "Minor Unit": 2,
  },
  {
    Country: "SVALBARD AND JAN MAYEN",
    Currency: "Norwegian Krone",
    "Alphabetic Code": "NOK",
    "Numeric Code": 578,
    "Minor Unit": 2,
  },
  {
    Country: "ESWATINI",
    Currency: "Lilangeni",
    "Alphabetic Code": "SZL",
    "Numeric Code": 748,
    "Minor Unit": 2,
  },
  {
    Country: "SWEDEN",
    Currency: "Swedish Krona",
    "Alphabetic Code": "SEK",
    "Numeric Code": 752,
    "Minor Unit": 2,
  },
  {
    Country: "SWITZERLAND",
    Currency: "Swiss Franc",
    "Alphabetic Code": "CHF",
    "Numeric Code": 756,
    "Minor Unit": 2,
  },
  {
    Country: "SWITZERLAND",
    Currency: "WIR Euro",
    "Alphabetic Code": "CHE",
    "Numeric Code": 947,
    "Minor Unit": 2,
  },
  {
    Country: "SWITZERLAND",
    Currency: "WIR Franc",
    "Alphabetic Code": "CHW",
    "Numeric Code": 948,
    "Minor Unit": 2,
  },
  {
    Country: "SYRIAN ARAB REPUBLIC",
    Currency: "Syrian Pound",
    "Alphabetic Code": "SYP",
    "Numeric Code": 760,
    "Minor Unit": 2,
  },
  {
    Country: "TAIWAN (PROVINCE OF CHINA)",
    Currency: "New Taiwan Dollar",
    "Alphabetic Code": "TWD",
    "Numeric Code": 901,
    "Minor Unit": 2,
  },
  {
    Country: "TAJIKISTAN",
    Currency: "Somoni",
    "Alphabetic Code": "TJS",
    "Numeric Code": 972,
    "Minor Unit": 2,
  },
  {
    Country: "TANZANIA, UNITED REPUBLIC OF",
    Currency: "Tanzanian Shilling",
    "Alphabetic Code": "TZS",
    "Numeric Code": 834,
    "Minor Unit": 2,
  },
  {
    Country: "THAILAND",
    Currency: "Baht",
    "Alphabetic Code": "THB",
    "Numeric Code": 764,
    "Minor Unit": 2,
  },
  {
    Country: "TIMOR-LESTE",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "TOGO",
    Currency: "CFA Franc BCEAO",
    "Alphabetic Code": "XOF",
    "Numeric Code": 952,
    "Minor Unit": 0,
  },
  {
    Country: "TOKELAU",
    Currency: "New Zealand Dollar",
    "Alphabetic Code": "NZD",
    "Numeric Code": 554,
    "Minor Unit": 2,
  },
  {
    Country: "TONGA",
    Currency: "Pa'anga",
    "Alphabetic Code": "TOP",
    "Numeric Code": 776,
    "Minor Unit": 2,
  },
  {
    Country: "TRINIDAD AND TOBAGO",
    Currency: "Trinidad and Tobago Dollar",
    "Alphabetic Code": "TTD",
    "Numeric Code": 780,
    "Minor Unit": 2,
  },
  {
    Country: "TUNISIA",
    Currency: "Tunisian Dinar",
    "Alphabetic Code": "TND",
    "Numeric Code": 788,
    "Minor Unit": 3,
  },
  {
    Country: "TURKEY",
    Currency: "Turkish Lira",
    "Alphabetic Code": "TRY",
    "Numeric Code": 949,
    "Minor Unit": 2,
  },
  {
    Country: "TURKMENISTAN",
    Currency: "Turkmenistan New Manat",
    "Alphabetic Code": "TMT",
    "Numeric Code": 934,
    "Minor Unit": 2,
  },
  {
    Country: "TURKS AND CAICOS ISLANDS (THE)",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "TUVALU",
    Currency: "Australian Dollar",
    "Alphabetic Code": "AUD",
    "Numeric Code": 36,
    "Minor Unit": 2,
  },
  {
    Country: "UGANDA",
    Currency: "Uganda Shilling",
    "Alphabetic Code": "UGX",
    "Numeric Code": 800,
    "Minor Unit": 0,
  },
  {
    Country: "UKRAINE",
    Currency: "Hryvnia",
    "Alphabetic Code": "UAH",
    "Numeric Code": 980,
    "Minor Unit": 2,
  },
  {
    Country: "UNITED ARAB EMIRATES (THE)",
    Currency: "UAE Dirham",
    "Alphabetic Code": "AED",
    "Numeric Code": 784,
    "Minor Unit": 2,
  },
  {
    Country: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)",
    Currency: "Pound Sterling",
    "Alphabetic Code": "GBP",
    "Numeric Code": 826,
    "Minor Unit": 2,
  },
  {
    Country: "UNITED STATES MINOR OUTLYING ISLANDS (THE)",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "UNITED STATES OF AMERICA (THE)",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "UNITED STATES OF AMERICA (THE)",
    Currency: "US Dollar (Next day)",
    "Alphabetic Code": "USN",
    "Numeric Code": 997,
    "Minor Unit": 2,
  },
  {
    Country: "URUGUAY",
    Currency: "Peso Uruguayo",
    "Alphabetic Code": "UYU",
    "Numeric Code": 858,
    "Minor Unit": 2,
  },
  {
    Country: "URUGUAY",
    Currency: "Uruguay Peso en Unidades Indexadas (UI)",
    "Alphabetic Code": "UYI",
    "Numeric Code": 940,
    "Minor Unit": 0,
  },
  {
    Country: "URUGUAY",
    Currency: "Unidad Previsional",
    "Alphabetic Code": "UYW",
    "Numeric Code": 927,
    "Minor Unit": 4,
  },
  {
    Country: "UZBEKISTAN",
    Currency: "Uzbekistan Sum",
    "Alphabetic Code": "UZS",
    "Numeric Code": 860,
    "Minor Unit": 2,
  },
  {
    Country: "VANUATU",
    Currency: "Vatu",
    "Alphabetic Code": "VUV",
    "Numeric Code": 548,
    "Minor Unit": 0,
  },
  {
    Country: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    Currency: "Bolívar Soberano",
    "Alphabetic Code": "VES",
    "Numeric Code": 928,
    "Minor Unit": 2,
  },
  {
    Country: "VIET NAM",
    Currency: "Dong",
    "Alphabetic Code": "VND",
    "Numeric Code": 704,
    "Minor Unit": 0,
  },
  {
    Country: "VIRGIN ISLANDS (BRITISH)",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "VIRGIN ISLANDS (U.S.)",
    Currency: "US Dollar",
    "Alphabetic Code": "USD",
    "Numeric Code": 840,
    "Minor Unit": 2,
  },
  {
    Country: "WALLIS AND FUTUNA",
    Currency: "CFP Franc",
    "Alphabetic Code": "XPF",
    "Numeric Code": 953,
    "Minor Unit": 0,
  },
  {
    Country: "WESTERN SAHARA",
    Currency: "Moroccan Dirham",
    "Alphabetic Code": "MAD",
    "Numeric Code": 504,
    "Minor Unit": 2,
  },
  {
    Country: "YEMEN",
    Currency: "Yemeni Rial",
    "Alphabetic Code": "YER",
    "Numeric Code": 886,
    "Minor Unit": 2,
  },
  {
    Country: "ZAMBIA",
    Currency: "Zambian Kwacha",
    "Alphabetic Code": "ZMW",
    "Numeric Code": 967,
    "Minor Unit": 2,
  },
  {
    Country: "ZIMBABWE",
    Currency: "Zimbabwe Dollar",
    "Alphabetic Code": "ZWL",
    "Numeric Code": 932,
    "Minor Unit": 2,
  },
  {
    Country: "ZZ01_Bond Markets Unit European_EURCO",
    Currency: "Bond Markets Unit European Composite Unit (EURCO)",
    "Alphabetic Code": "XBA",
    "Numeric Code": 955,
    "Minor Unit": "NA",
  },
  {
    Country: "ZZ02_Bond Markets Unit European_EMU-6",
    Currency: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
    "Alphabetic Code": "XBB",
    "Numeric Code": 956,
    "Minor Unit": "NA",
  },
  {
    Country: "ZZ03_Bond Markets Unit European_EUA-9",
    Currency: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
    "Alphabetic Code": "XBC",
    "Numeric Code": 957,
    "Minor Unit": "NA",
  },
  {
    Country: "ZZ04_Bond Markets Unit European_EUA-17",
    Currency: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
    "Alphabetic Code": "XBD",
    "Numeric Code": 958,
    "Minor Unit": "NA",
  },
  {
    Country: "ZZ06_Testing_Code",
    Currency: "Codes specifically reserved for testing purposes",
    "Alphabetic Code": "XTS",
    "Numeric Code": 963,
    "Minor Unit": "NA",
  },
  {
    Country: "ZZ07_No_Currency",
    Currency: "The codes assigned for transactions where no currency is involved",
    "Alphabetic Code": "XXX",
    "Numeric Code": 999,
    "Minor Unit": "NA",
  },
  {
    Country: "ZZ08_Gold",
    Currency: "Gold",
    "Alphabetic Code": "XAU",
    "Numeric Code": 959,
    "Minor Unit": "NA",
  },
  {
    Country: "ZZ09_Palladium",
    Currency: "Palladium",
    "Alphabetic Code": "XPD",
    "Numeric Code": 964,
    "Minor Unit": "NA",
  },
  {
    Country: "ZZ10_Platinum",
    Currency: "Platinum",
    "Alphabetic Code": "XPT",
    "Numeric Code": 962,
    "Minor Unit": "NA",
  },
  {
    Country: "ZZ11_Silver",
    Currency: "Silver",
    "Alphabetic Code": "XAG",
    "Numeric Code": 961,
    "Minor Unit": "NA",
  },
];

export const CURRENCY_CODE_LIST = {
  AFGHANISTAN: "AFN",
  "ÅLAND ISLANDS": "EUR",
  ALBANIA: "ALL",
  ALGERIA: "DZD",
  "AMERICAN SAMOA": "USD",
  ANDORRA: "EUR",
  ANGOLA: "AOA",
  ANGUILLA: "XCD",
  ANTARCTICA: "",
  "ANTIGUA AND BARBUDA": "XCD",
  ARGENTINA: "ARS",
  ARMENIA: "AMD",
  ARUBA: "AWG",
  AUSTRALIA: "AUD",
  AUSTRIA: "EUR",
  AZERBAIJAN: "AZN",
  "BAHAMAS (THE)": "BSD",
  BAHRAIN: "BHD",
  BANGLADESH: "BDT",
  BARBADOS: "BBD",
  BELARUS: "BYN",
  BELGIUM: "EUR",
  BELIZE: "BZD",
  BENIN: "XOF",
  BERMUDA: "BMD",
  BHUTAN: "BTN",
  "BOLIVIA (PLURINATIONAL STATE OF)": "BOV",
  "BONAIRE, SINT EUSTATIUS AND SABA": "USD",
  "BOSNIA AND HERZEGOVINA": "BAM",
  BOTSWANA: "BWP",
  "BOUVET ISLAND": "NOK",
  BRAZIL: "BRL",
  "BRITISH INDIAN OCEAN TERRITORY (THE)": "USD",
  "BRUNEI DARUSSALAM": "BND",
  BULGARIA: "BGN",
  "BURKINA FASO": "XOF",
  BURUNDI: "BIF",
  "CABO VERDE": "CVE",
  CAMBODIA: "KHR",
  CAMEROON: "XAF",
  CANADA: "CAD",
  "CAYMAN ISLANDS (THE)": "KYD",
  "CENTRAL AFRICAN REPUBLIC (THE)": "XAF",
  CHAD: "XAF",
  CHILE: "CLF",
  CHINA: "CNY",
  "CHRISTMAS ISLAND": "AUD",
  "COCOS (KEELING) ISLANDS (THE)": "AUD",
  COLOMBIA: "COU",
  "COMOROS (THE)": "KMF",
  "CONGO (THE DEMOCRATIC REPUBLIC OF THE)": "CDF",
  "CONGO (THE)": "XAF",
  "COOK ISLANDS (THE)": "NZD",
  "COSTA RICA": "CRC",
  "CÔTE D'IVOIRE": "XOF",
  CROATIA: "HRK",
  CUBA: "CUC",
  CURAÇAO: "ANG",
  CYPRUS: "EUR",
  CZECHIA: "CZK",
  DENMARK: "DKK",
  DJIBOUTI: "DJF",
  DOMINICA: "XCD",
  "DOMINICAN REPUBLIC (THE)": "DOP",
  ECUADOR: "USD",
  EGYPT: "EGP",
  "EL SALVADOR": "USD",
  "EQUATORIAL GUINEA": "XAF",
  ERITREA: "ERN",
  ESTONIA: "EUR",
  ETHIOPIA: "ETB",
  "EUROPEAN UNION": "EUR",
  "FALKLAND ISLANDS (THE) [MALVINAS]": "FKP",
  "FAROE ISLANDS (THE)": "DKK",
  FIJI: "FJD",
  FINLAND: "EUR",
  FRANCE: "EUR",
  "FRENCH GUIANA": "EUR",
  "FRENCH POLYNESIA": "XPF",
  "FRENCH SOUTHERN TERRITORIES (THE)": "EUR",
  GABON: "XAF",
  "GAMBIA (THE)": "GMD",
  GEORGIA: "GEL",
  GERMANY: "EUR",
  GHANA: "GHS",
  GIBRALTAR: "GIP",
  GREECE: "EUR",
  GREENLAND: "DKK",
  GRENADA: "XCD",
  GUADELOUPE: "EUR",
  GUAM: "USD",
  GUATEMALA: "GTQ",
  GUERNSEY: "GBP",
  GUINEA: "GNF",
  "GUINEA-BISSAU": "XOF",
  GUYANA: "GYD",
  HAITI: "USD",
  "HEARD ISLAND AND McDONALD ISLANDS": "AUD",
  "HOLY SEE (THE)": "EUR",
  HONDURAS: "HNL",
  "HONG KONG": "HKD",
  HUNGARY: "HUF",
  ICELAND: "ISK",
  INDIA: "INR",
  INDONESIA: "IDR",
  "INTERNATIONAL MONETARY FUND (IMF)": "XDR",
  "IRAN (ISLAMIC REPUBLIC OF)": "IRR",
  IRAQ: "IQD",
  IRELAND: "EUR",
  "ISLE OF MAN": "GBP",
  ISRAEL: "ILS",
  ITALY: "EUR",
  JAMAICA: "JMD",
  JAPAN: "JPY",
  JERSEY: "GBP",
  JORDAN: "JOD",
  KAZAKHSTAN: "KZT",
  KENYA: "KES",
  KIRIBATI: "AUD",
  "KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)": "KPW",
  "KOREA (THE REPUBLIC OF)": "KRW",
  KUWAIT: "KWD",
  KYRGYZSTAN: "KGS",
  "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)": "LAK",
  LATVIA: "EUR",
  LEBANON: "LBP",
  LESOTHO: "ZAR",
  LIBERIA: "LRD",
  LIBYA: "LYD",
  LIECHTENSTEIN: "CHF",
  LITHUANIA: "EUR",
  LUXEMBOURG: "EUR",
  MACAO: "MOP",
  "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)": "MKD",
  MADAGASCAR: "MGA",
  MALAWI: "MWK",
  MALAYSIA: "MYR",
  MALDIVES: "MVR",
  MALI: "XOF",
  MALTA: "EUR",
  "MARSHALL ISLANDS (THE)": "USD",
  MARTINIQUE: "EUR",
  MAURITANIA: "MRU",
  MAURITIUS: "MUR",
  MAYOTTE: "EUR",
  "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP": "XUA",
  MEXICO: "MXV",
  "MICRONESIA (FEDERATED STATES OF)": "USD",
  "MOLDOVA (THE REPUBLIC OF)": "MDL",
  MONACO: "EUR",
  MONGOLIA: "MNT",
  MONTENEGRO: "EUR",
  MONTSERRAT: "XCD",
  MOROCCO: "MAD",
  MOZAMBIQUE: "MZN",
  MYANMAR: "MMK",
  NAMIBIA: "ZAR",
  NAURU: "AUD",
  NEPAL: "NPR",
  "NETHERLANDS (THE)": "EUR",
  "NEW CALEDONIA": "XPF",
  "NEW ZEALAND": "NZD",
  NICARAGUA: "NIO",
  "NIGER (THE)": "XOF",
  NIGERIA: "NGN",
  NIUE: "NZD",
  "NORFOLK ISLAND": "AUD",
  "NORTHERN MARIANA ISLANDS (THE)": "USD",
  NORWAY: "NOK",
  OMAN: "OMR",
  PAKISTAN: "PKR",
  PALAU: "USD",
  "PALESTINE, STATE OF": "",
  PANAMA: "USD",
  "PAPUA NEW GUINEA": "PGK",
  PARAGUAY: "PYG",
  PERU: "PEN",
  "PHILIPPINES (THE)": "PHP",
  PITCAIRN: "NZD",
  POLAND: "PLN",
  PORTUGAL: "EUR",
  "PUERTO RICO": "USD",
  QATAR: "QAR",
  RÉUNION: "EUR",
  ROMANIA: "RON",
  "RUSSIAN FEDERATION (THE)": "RUB",
  RWANDA: "RWF",
  "SAINT BARTHÉLEMY": "EUR",
  "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA": "SHP",
  "SAINT KITTS AND NEVIS": "XCD",
  "SAINT LUCIA": "XCD",
  "SAINT MARTIN (FRENCH PART)": "EUR",
  "SAINT PIERRE AND MIQUELON": "EUR",
  "SAINT VINCENT AND THE GRENADINES": "XCD",
  SAMOA: "WST",
  "SAN MARINO": "EUR",
  "SAO TOME AND PRINCIPE": "STN",
  "SAUDI ARABIA": "SAR",
  SENEGAL: "XOF",
  SERBIA: "RSD",
  SEYCHELLES: "SCR",
  "SIERRA LEONE": "SLL",
  SINGAPORE: "SGD",
  "SINT MAARTEN (DUTCH PART)": "ANG",
  'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE': "XSU",
  SLOVAKIA: "EUR",
  SLOVENIA: "EUR",
  "SOLOMON ISLANDS": "SBD",
  SOMALIA: "SOS",
  "SOUTH AFRICA": "ZAR",
  "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS": "",
  "SOUTH SUDAN": "SSP",
  SPAIN: "EUR",
  "SRI LANKA": "LKR",
  "SUDAN (THE)": "SDG",
  SURINAME: "SRD",
  "SVALBARD AND JAN MAYEN": "NOK",
  ESWATINI: "SZL",
  SWEDEN: "SEK",
  SWITZERLAND: "CHW",
  "SYRIAN ARAB REPUBLIC": "SYP",
  "TAIWAN (PROVINCE OF CHINA)": "TWD",
  TAJIKISTAN: "TJS",
  "TANZANIA, UNITED REPUBLIC OF": "TZS",
  THAILAND: "THB",
  "TIMOR-LESTE": "USD",
  TOGO: "XOF",
  TOKELAU: "NZD",
  TONGA: "TOP",
  "TRINIDAD AND TOBAGO": "TTD",
  TUNISIA: "TND",
  TURKEY: "TRY",
  TURKMENISTAN: "TMT",
  "TURKS AND CAICOS ISLANDS (THE)": "USD",
  TUVALU: "AUD",
  UGANDA: "UGX",
  UKRAINE: "UAH",
  "UNITED ARAB EMIRATES (THE)": "AED",
  "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)": "GBP",
  "UNITED STATES MINOR OUTLYING ISLANDS (THE)": "USD",
  "UNITED STATES OF AMERICA (THE)": "USN",
  URUGUAY: "UYW",
  UZBEKISTAN: "UZS",
  VANUATU: "VUV",
  "VENEZUELA (BOLIVARIAN REPUBLIC OF)": "VES",
  "VIET NAM": "VND",
  "VIRGIN ISLANDS (BRITISH)": "USD",
  "VIRGIN ISLANDS (U.S.)": "USD",
  "WALLIS AND FUTUNA": "XPF",
  "WESTERN SAHARA": "MAD",
  YEMEN: "YER",
  ZAMBIA: "ZMW",
  ZIMBABWE: "ZWL",
  "ZZ01_Bond Markets Unit European_EURCO": "XBA",
  "ZZ02_Bond Markets Unit European_EMU-6": "XBB",
  "ZZ03_Bond Markets Unit European_EUA-9": "XBC",
  "ZZ04_Bond Markets Unit European_EUA-17": "XBD",
  ZZ06_Testing_Code: "XTS",
  ZZ07_No_Currency: "XXX",
  ZZ08_Gold: "XAU",
  ZZ09_Palladium: "XPD",
  ZZ10_Platinum: "XPT",
  ZZ11_Silver: "XAG",
};
