//List Actions
export const FETCH_LISTDEMO_BEGIN = "FETCH_LISTDEMO_BEGIN";
export const FETCH_LISTDEMO_SUCCESS = "FETCH_LISTDEMO_SUCCESS";
export const FETCH_LISTDEMO_FAILURE = "FETCH_LISTDEMO_FAILURE";
//Other Actions...

export const COUNT_BEGIN = "COUNT_BEGIN";
export const COUNT_SUCCESS = "COUNT_SUCCESS";
export const COUNT_FAILURE = "COUNT_FAILURE";
